spring:
    application:
        name: fileviewerapplication
    servlet:
        multipart:
            enabled: true
            max-file-size: 2048MB
            max-request-size: 2048MB
    thymeleaf:
        cache: true
        mode: HTML
        check-template: true
        check-template-location: true
        prefix: classpath:/templates/
        suffix: .html
    web:
        resources:
            cache:
                cachecontrol:
                    max-age: 365d
                    cache-public: true
            chain:
                enabled: true
                strategy:
                    control:
                        enabled: true
                        paths: /**
server:
    port: 8080
    tomcat:
        threads:
            min-spare: 20
            max: 200
        accept-count: 200
    max-http-header-size: 16KB
viewer:
  recordLength: 255
  charset: Cp037
  prefixIndexLength: 10
  index:
    workers: 4
    progressStep: 8192
  export:
    bufferSize: 1048576
  chunk:
    enabled: true
    windowSizeMB: 512
