package com.its255.schema;

import static com.its255.schema.FieldType.ALPHA;
import static com.its255.schema.FieldType.NUMERIC_TEXT;
import static com.its255.schema.FieldType.PACKED_DECIMAL;

import java.util.List;


public final class CapitatedBillingSchemas {
	
	
	public static final List<FieldSpec> FM35A = List.of(
		    new FieldSpec("FM35A-BATCH-NUM", 1, 14, ALPHA),
		    new FieldSpec("FM35A-FILLER-1", 15, 5, ALPHA),
		    new FieldSpec("FM35A-TRANS-ID", 20, 2, ALPHA),
		    new FieldSpec("FM35A-REC-TYPE", 22, 2, ALPHA),
		    new FieldSpec("FM35A-SEQ-NUM", 24, 2, NUMERIC_TEXT),
		    new FieldSpec("FM35A-ORGN-PLAN-CD", 26, 3, ALPHA),
		    new FieldSpec("FM35A-ORGN-PLAN-STA-CD", 29, 4, ALPHA),
		    new FieldSpec("FM35A-DEST-PLAN-CD", 33, 3, ALPHA),
		    new FieldSpec("FM35A-DEST-PLAN-STA-CD", 36, 4, ALPHA),
		    new FieldSpec("FM35A-CB-BILL-START-DT-CC", 40, 2, ALPHA),
		    new FieldSpec("FM35A-CB-BILL-START-DT-YY", 42, 2, ALPHA),
		    new FieldSpec("FM35A-CB-BILL-START-DT-MM", 44, 2, ALPHA),
		    new FieldSpec("FM35A-CB-BILL-START-DT-DD", 46, 2, ALPHA),
		    new FieldSpec("FM35A-CB-BILL-END-DT-CC", 48, 2, ALPHA),
		    new FieldSpec("FM35A-CB-BILL-END-DT-YY", 50, 2, ALPHA),
		    new FieldSpec("FM35A-CB-BILL-END-DT-MM", 52, 2, ALPHA),
		    new FieldSpec("FM35A-CB-BILL-END-DT-DD", 54, 2, ALPHA),
		    new FieldSpec("FM35A-MEMBER-COMP-DT-CC", 56, 2, ALPHA),
		    new FieldSpec("FM35A-MEMBER-COMP-DT-YY", 58, 2, ALPHA),
		    new FieldSpec("FM35A-MEMBER-COMP-DT-MM", 60, 2, ALPHA),
		    new FieldSpec("FM35A-MEMBER-COMP-DT-DD", 62, 2, ALPHA),
		    new FieldSpec("FM35A-FILE-CREATE-DT-CC", 64, 2, ALPHA),
		    new FieldSpec("FM35A-FILE-CREATE-DT-YY", 66, 2, ALPHA),
		    new FieldSpec("FM35A-FILE-CREATE-DT-MM", 68, 2, ALPHA),
		    new FieldSpec("FM35A-FILE-CREATE-DT-DD", 70, 2, ALPHA),
		    new FieldSpec("FM35A-FILE-CREATE-TIME-HH", 72, 2, ALPHA),
		    new FieldSpec("FM35A-FILE-CREATE-TIME-MM", 74, 2, ALPHA),
		    new FieldSpec("FM35A-FILE-CREATE-TIME-SS", 76, 2, ALPHA),
		    new FieldSpec("FM35A-BATCH-STATUS-CD", 78, 1, ALPHA),
		    new FieldSpec("FM35A-BATCH-CREATE-DT-CC", 79, 2, ALPHA),
		    new FieldSpec("FM35A-BATCH-CREATE-DT-YY", 81, 2, ALPHA),
		    new FieldSpec("FM35A-BATCH-CREATE-DT-MM", 83, 2, ALPHA),
		    new FieldSpec("FM35A-BATCH-CREATE-DT-DD", 85, 2, ALPHA),
		    new FieldSpec("FM35A-HOME-AUTH-DEN-DT-CC", 87, 2, ALPHA),
		    new FieldSpec("FM35A-HOME-AUTH-DEN-DT-YY", 89, 2, ALPHA),
		    new FieldSpec("FM35A-HOME-AUTH-DEN-DT-MM", 91, 2, ALPHA),
		    new FieldSpec("FM35A-HOME-AUTH-DEN-DT-DD", 93, 2, ALPHA),
		    new FieldSpec("FM35A-CFA-DISP-DT-CC", 95, 2, ALPHA),
		    new FieldSpec("FM35A-CFA-DISP-DT-YY", 97, 2, ALPHA),
		    new FieldSpec("FM35A-CFA-DISP-DT-MM", 99, 2, ALPHA),
		    new FieldSpec("FM35A-CFA-DISP-DT-DD", 101, 2, ALPHA),
		    new FieldSpec("FM35A-CFA-DEFLT-PMT-DT-CC", 103, 2, ALPHA),
		    new FieldSpec("FM35A-CFA-DEFLT-PMT-DT-YY", 105, 2, ALPHA),
		    new FieldSpec("FM35A-CFA-DEFLT-PMT-DT-MM", 107, 2, ALPHA),
		    new FieldSpec("FM35A-CFA-DEFLT-PMT-DT-DD", 109, 2, ALPHA),
		    new FieldSpec("FM35A-CFA-PRCSS-DT-CC", 111, 2, ALPHA),
		    new FieldSpec("FM35A-CFA-PRCSS-DT-YY", 113, 2, ALPHA),
		    new FieldSpec("FM35A-CFA-PRCSS-DT-MM", 115, 2, ALPHA),
		    new FieldSpec("FM35A-CFA-PRCSS-DT-DD", 117, 2, ALPHA),
		    new FieldSpec("FM35A-CFA-CNTL-NUM", 119, 14, ALPHA),
		    new FieldSpec("FM35A-DEST-PLAN-CFA-ACCT-CD", 133, 2, ALPHA),
		    new FieldSpec("FM35A-ORGN-PLAN-CFA-ACCT-CD", 135, 2, ALPHA),
		    new FieldSpec("FM35A-TYPE-CFA-REIMB", 137, 1, ALPHA),
		    new FieldSpec("FM35A-TYPE-CFA-TRANS", 138, 2, ALPHA),
		    new FieldSpec("FM35A-TRANS-ORGN", 140, 1, ALPHA),
		    new FieldSpec("FM35A-ERR-CD-1", 141, 5, ALPHA),
		    new FieldSpec("FM35A-ERR-CD-2", 146, 5, ALPHA),
		    new FieldSpec("FM35A-ERR-CD-3", 151, 5, ALPHA),
		    new FieldSpec("FM35A-ERR-CD-4", 156, 5, ALPHA),
		    new FieldSpec("FM35A-ERR-CD-5", 161, 5, ALPHA),
		    new FieldSpec("FM35A-FUND-POOL", 166, 3, ALPHA),
		    new FieldSpec("FM35A-PGM-CD", 169, 1, ALPHA),
		    new FieldSpec("FM35A-DEL-MTH", 170, 1, ALPHA),
		    new FieldSpec("FM35A-NAT-OOA-CD", 171, 1, ALPHA),
		    new FieldSpec("FM35A-ACCT-TYPE-CD", 172, 1, ALPHA),
		    new FieldSpec("FM35A-FILLER-2", 173, 83, ALPHA)
		);
	
	public static final List<FieldSpec> FM36A = List.of(
		    new FieldSpec("FM36A-SUB-ID-PFX-1-3", 1, 3, ALPHA),
		    new FieldSpec("FM36A-SUB-ID-SUFX-4-17", 4, 14, ALPHA),
		    new FieldSpec("FM36A-SUB-DEP-IDENTIFIER", 18, 2, ALPHA),
		    new FieldSpec("FM36A-TRANS-ID", 20, 2, ALPHA),
		    new FieldSpec("FM36A-REC-TYPE", 22, 2, ALPHA),
		    new FieldSpec("FM36A-SEQ-NUM", 24, 2, NUMERIC_TEXT),
		    new FieldSpec("FM36A-CNTL-PLAN-CD", 26, 3, ALPHA),
		    new FieldSpec("FM36A-PROC-SITE-STA-CD", 29, 4, ALPHA),
		    new FieldSpec("FM36A-LOC-PLAN-CD", 33, 3, ALPHA),
		    new FieldSpec("FM36A-LOC-PLAN-STA-CD", 36, 4, ALPHA),
		    new FieldSpec("FM36A-CNTL-PLAN-CFA-ACCT-CD", 40, 2, ALPHA),
		    new FieldSpec("FM36A-LOC-PLAN-CFA-ACCT-CD", 42, 2, ALPHA),
		    new FieldSpec("FM36A-PRODUCT-CD", 44, 2, ALPHA),
		    new FieldSpec("FM36A-REL-NUM", 46, 3, ALPHA),
		    new FieldSpec("FM36A-PAT-REL-TO-SUB", 49, 2, ALPHA),
		    new FieldSpec("FM36A-SUB-GRP-NUM", 51, 9, ALPHA),
		    new FieldSpec("FM36A-SUB-GRP-SECTION-NUM", 60, 6, ALPHA),
		    new FieldSpec("FM36A-SUB-FIRST-NAME", 66, 10, ALPHA),
		    new FieldSpec("FM36A-SUB-LAST-NAME", 76, 20, ALPHA),
		    new FieldSpec("FM36A-SUB-MID-INIT", 96, 1, ALPHA),
		    new FieldSpec("FM36A-SUB-SEX", 97, 1, ALPHA),
		    new FieldSpec("FM36A-SUB-BRT-DT-CC", 98, 2, ALPHA),
		    new FieldSpec("FM36A-SUB-BRT-DT-YY", 100, 2, ALPHA),
		    new FieldSpec("FM36A-SUB-BRT-DT-MM", 102, 2, ALPHA),
		    new FieldSpec("FM36A-SUB-BRT-DT-DD", 104, 2, ALPHA),
		    new FieldSpec("FM36A-PROV-PLAN-CD", 106, 3, ALPHA),
		    new FieldSpec("FM36A-FILLER-1", 109, 2, ALPHA),
		    new FieldSpec("FM36A-PCP-NUMBER", 111, 13, ALPHA),
		    new FieldSpec("FM36A-PCP-NUMBER-SFX", 124, 2, ALPHA),
		    new FieldSpec("FM36A-CB-PROV-IND", 126, 1, ALPHA),
		    new FieldSpec("FM36A-CB-BILL-START-DT-CC", 127, 2, ALPHA),
		    new FieldSpec("FM36A-CB-BILL-START-DT-YY", 129, 2, ALPHA),
		    new FieldSpec("FM36A-CB-BILL-START-DT-MM", 131, 2, ALPHA),
		    new FieldSpec("FM36A-CB-BILL-START-DT-DD", 133, 2, ALPHA),
		    new FieldSpec("FM36A-CB-BILL-END-DT-CC", 135, 2, ALPHA),
		    new FieldSpec("FM36A-CB-BILL-END-DT-YY", 137, 2, ALPHA),
		    new FieldSpec("FM36A-CB-BILL-END-DT-MM", 139, 2, ALPHA),
		    new FieldSpec("FM36A-CB-BILL-END-DT-DD", 141, 2, ALPHA),
		    new FieldSpec("FM36A-FUND-POOL", 143, 3, ALPHA),
		    new FieldSpec("FM36A-ADJUST-IND", 146, 2, ALPHA),
		    new FieldSpec("FM36A-CB-RATE-AMT", 148, 6, PACKED_DECIMAL, 2),
		    new FieldSpec("FM36A-TRANS-DT-CC", 154, 2, ALPHA),
		    new FieldSpec("FM36A-TRANS-DT-YY", 156, 2, ALPHA),
		    new FieldSpec("FM36A-TRANS-DT-MM", 158, 2, ALPHA),
		    new FieldSpec("FM36A-TRANS-DT-DD", 160, 2, ALPHA),
		    new FieldSpec("FM36A-INVOICE-NUM", 162, 8, ALPHA),
		    new FieldSpec("FM36A-FED-TAX-ID", 170, 9, ALPHA),
		    new FieldSpec("FM36A-DT-PAID-CC", 179, 2, ALPHA),
		    new FieldSpec("FM36A-DT-PAID-YY", 181, 2, ALPHA),
		    new FieldSpec("FM36A-DT-PAID-MM", 183, 2, ALPHA),
		    new FieldSpec("FM36A-DT-PAID-DD", 185, 2, ALPHA),
		    new FieldSpec("FM36A-PROV-NETWORK-ID", 187, 4, ALPHA),
		    new FieldSpec("FM36A-PAR-PLAN-GRP-NUM", 191, 9, ALPHA),
		    new FieldSpec("FM36A-CAP-SUPPL-AMT", 200, 6, PACKED_DECIMAL, 2),
		    new FieldSpec("FM36A-CAP-SURCHG-AMT", 206, 6, PACKED_DECIMAL, 2),
		    new FieldSpec("FM36A-NET-CB-AMT", 212, 6, PACKED_DECIMAL, 2),
		    new FieldSpec("FM36A-ADJ-RSN-CD", 218, 2, ALPHA),
		    new FieldSpec("FM36A-PGM-CD", 220, 1, ALPHA),
		    new FieldSpec("FM36A-DEL-MTH", 221, 1, ALPHA),
		    new FieldSpec("FM36A-NAT-OOA-CD", 222, 1, ALPHA),
		    new FieldSpec("FM36A-ACCT-TYPE-CD", 223, 1, ALPHA),
		    new FieldSpec("FM36A-FILLER-2", 224, 32, ALPHA)
		);
	
	public static final List<FieldSpec> FM36B = List.of(
		    new FieldSpec("FM36B-SUB-ID-PFX-1-3", 1, 3, ALPHA),
		    new FieldSpec("FM36B-SUB-ID-SUFX-4-17", 4, 14, ALPHA),
		    new FieldSpec("FM36B-SUB-DEP-IDENTIFIER", 18, 2, ALPHA),
		    new FieldSpec("FM36B-TRANS-ID", 20, 2, ALPHA),
		    new FieldSpec("FM36B-REC-TYPE", 22, 2, ALPHA),
		    new FieldSpec("FM36B-SEQ-NUM", 24, 2, NUMERIC_TEXT),
		    new FieldSpec("FM36B-BATCH-NUM", 26, 14, ALPHA),
		    new FieldSpec("FM36B-BATCH-CREATE-DT-CC", 40, 2, ALPHA),
		    new FieldSpec("FM36B-BATCH-CREATE-DT-YY", 42, 2, ALPHA),
		    new FieldSpec("FM36B-BATCH-CREATE-DT-MM", 44, 2, ALPHA),
		    new FieldSpec("FM36B-BATCH-CREATE-DT-DD", 46, 2, ALPHA),
		    new FieldSpec("FM36B-HOME-AUTH-DEN-DT-CC", 48, 2, ALPHA),
		    new FieldSpec("FM36B-HOME-AUTH-DEN-DT-YY", 50, 2, ALPHA),
		    new FieldSpec("FM36B-HOME-AUTH-DEN-DT-MM", 52, 2, ALPHA),
		    new FieldSpec("FM36B-HOME-AUTH-DEN-DT-DD", 54, 2, ALPHA),
		    new FieldSpec("FM36B-CFA-DISP-DT-CC", 56, 2, ALPHA),
		    new FieldSpec("FM36B-CFA-DISP-DT-YY", 58, 2, ALPHA),
		    new FieldSpec("FM36B-CFA-DISP-DT-MM", 60, 2, ALPHA),
		    new FieldSpec("FM36B-CFA-DISP-DT-DD", 62, 2, ALPHA),
		    new FieldSpec("FM36B-CFA-DEFLT-PMT-DT-CC", 64, 2, ALPHA),
		    new FieldSpec("FM36B-CFA-DEFLT-PMT-DT-YY", 66, 2, ALPHA),
		    new FieldSpec("FM36B-CFA-DEFLT-PMT-DT-MM", 68, 2, ALPHA),
		    new FieldSpec("FM36B-CFA-DEFLT-PMT-DT-DD", 70, 2, ALPHA),
		    new FieldSpec("FM36B-CFA-PRCSS-DT-CC", 72, 2, ALPHA),
		    new FieldSpec("FM36B-CFA-PRCSS-DT-YY", 74, 2, ALPHA),
		    new FieldSpec("FM36B-CFA-PRCSS-DT-MM", 76, 2, ALPHA),
		    new FieldSpec("FM36B-CFA-PRCSS-DT-DD", 78, 2, ALPHA),
		    new FieldSpec("FM36B-ERR-CD-1", 80, 5, ALPHA),
		    new FieldSpec("FM36B-ERR-CD-2", 85, 5, ALPHA),
		    new FieldSpec("FM36B-ERR-CD-3", 90, 5, ALPHA),
		    new FieldSpec("FM36B-ERR-CD-4", 95, 5, ALPHA),
		    new FieldSpec("FM36B-ERR-CD-5", 100, 5, ALPHA),
		    new FieldSpec("FM36B-STATUS-CD", 105, 1, ALPHA),
		    new FieldSpec("FM36B-CFA-STAT-CD", 106, 1, ALPHA),
		    new FieldSpec("FM36B-EDIT-DT-CC", 107, 2, ALPHA),
		    new FieldSpec("FM36B-EDIT-DT-YY", 109, 2, ALPHA),
		    new FieldSpec("FM36B-EDIT-DT-MM", 111, 2, ALPHA),
		    new FieldSpec("FM36B-EDIT-DT-DD", 113, 2, ALPHA),
		    new FieldSpec("FM36B-TYPE-CFA-REIMB", 115, 1, ALPHA),
		    new FieldSpec("FM36B-TYPE-CFA-TRANS", 116, 2, ALPHA),
		    new FieldSpec("FM36B-TRANS-IND", 118, 1, ALPHA),
		    new FieldSpec("FM36B-FILLER", 119, 137, ALPHA)
		);
	
	public static final List<FieldSpec> FM37A = List.of(
		    new FieldSpec("FM37A-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
		    new FieldSpec("FM37A-SER-NUM-JULDT-CC", 4, 2, NUMERIC_TEXT),
		    new FieldSpec("FM37A-SER-NUM-JULDT-YY", 6, 2, NUMERIC_TEXT),
		    new FieldSpec("FM37A-SER-NUM-JULDT-DDD", 8, 3, NUMERIC_TEXT),
		    new FieldSpec("FM37A-SER-NUM-SEQUENCE", 11, 5, NUMERIC_TEXT),
		    new FieldSpec("FM37A-SER-NUM-JULIAN-DATE-9", 4, 7, NUMERIC_TEXT),
		    new FieldSpec("FM37A-SER-NUM-SUFFIX", 16, 2, NUMERIC_TEXT),
		    new FieldSpec("FM37A-FILLER-1", 18, 2, ALPHA),
		    new FieldSpec("FM37A-TRANS-ID", 20, 2, ALPHA),
		    new FieldSpec("FM37A-REC-TYPE", 22, 2, ALPHA),
		    new FieldSpec("FM37A-SEQ-NUM", 24, 2, NUMERIC_TEXT),
		    new FieldSpec("FM37A-CNTL-PLAN-CD", 26, 3, ALPHA),
		    new FieldSpec("FM37A-PROC-SITE-STA-CD", 29, 4, ALPHA),
		    new FieldSpec("FM37A-LOC-PLAN-CD", 33, 3, ALPHA),
		    new FieldSpec("FM37A-LOC-PLAN-STA-CD", 36, 4, ALPHA),
		    new FieldSpec("FM37A-CNTL-PLAN-CFA-ACCT-CD", 40, 2, ALPHA),
		    new FieldSpec("FM37A-LOC-PLAN-CFA-ACCT-CD", 42, 2, ALPHA),
		    new FieldSpec("FM37A-SUB-ID-PFX-1-3", 44, 3, ALPHA),
		    new FieldSpec("FM37A-SUB-ID-SUFX-4-17", 47, 14, ALPHA),
		    new FieldSpec("FM37A-SUB-GRP-NUM", 61, 9, ALPHA),
		    new FieldSpec("FM37A-ADM-SERV-DT-CC", 70, 2, ALPHA),
		    new FieldSpec("FM37A-ADM-SERV-DT-YY", 72, 2, ALPHA),
		    new FieldSpec("FM37A-ADM-SERV-DT-MM", 74, 2, ALPHA),
		    new FieldSpec("FM37A-ADM-SERV-DT-DD", 76, 2, ALPHA),
		    new FieldSpec("FM37A-NET-CB-AMT", 78, 6, PACKED_DECIMAL, 2),
		    new FieldSpec("FM37A-ADMIN-EXP-ALLW", 84, 5, PACKED_DECIMAL, 2),
		    new FieldSpec("FM37A-ACCESS-FEE-AMT", 89, 5, PACKED_DECIMAL, 2),
		    new FieldSpec("FM37A-FILLER-2", 94, 5, ALPHA),
		    new FieldSpec("FM37A-CLM-CONTRACT-CNT", 99, 5, PACKED_DECIMAL, 0),
		    new FieldSpec("FM37A-PROV-NUM", 104, 13, ALPHA),
		    new FieldSpec("FM37A-LOC-PLAN-CNTL-NUM", 117, 17, ALPHA),
		    new FieldSpec("FM37A-LOC-PLAN-CLM-REF-NUM", 134, 17, ALPHA),
		    new FieldSpec("FM37A-PROC-SITE-CNTL-NUM", 151, 17, ALPHA),
		    new FieldSpec("FM37A-CLM-TYPE", 168, 2, ALPHA),
		    new FieldSpec("FM37A-SUP-PAID-DT-CC", 170, 2, ALPHA),
		    new FieldSpec("FM37A-SUP-PAID-DT-YY", 172, 2, ALPHA),
		    new FieldSpec("FM37A-SUP-PAID-DT-MM", 174, 2, ALPHA),
		    new FieldSpec("FM37A-SUP-PAID-DT-DD", 176, 2, ALPHA),
		    new FieldSpec("FM37A-TRANS-DT-CC", 178, 2, ALPHA),
		    new FieldSpec("FM37A-TRANS-DT-YY", 180, 2, ALPHA),
		    new FieldSpec("FM37A-TRANS-DT-MM", 182, 2, ALPHA),
		    new FieldSpec("FM37A-TRANS-DT-DD", 184, 2, ALPHA),
		    new FieldSpec("FM37A-INVOICE-NUM", 186, 8, ALPHA),
		    new FieldSpec("FM37A-TRANS-ORGN", 194, 1, ALPHA),
		    new FieldSpec("FM37A-REL-NUM", 195, 3, ALPHA),
		    new FieldSpec("FM37A-PGM-CD", 198, 1, ALPHA),
		    new FieldSpec("FM37A-DEL-MTH", 199, 1, ALPHA),
		    new FieldSpec("FM37A-NAT-OOA-CD", 200, 1, ALPHA),
		    new FieldSpec("FM37A-CB-BILL-START-DT-CC", 201, 2, ALPHA),
		    new FieldSpec("FM37A-CB-BILL-START-DT-YY", 203, 2, ALPHA),
		    new FieldSpec("FM37A-CB-BILL-START-DT-MM", 205, 2, ALPHA),
		    new FieldSpec("FM37A-CB-BILL-START-DT-DD", 207, 2, ALPHA),
		    new FieldSpec("FM37A-CB-BILL-END-DT-CC", 209, 2, ALPHA),
		    new FieldSpec("FM37A-CB-BILL-END-DT-YY", 211, 2, ALPHA),
		    new FieldSpec("FM37A-CB-BILL-END-DT-MM", 213, 2, ALPHA),
		    new FieldSpec("FM37A-CB-BILL-END-DT-DD", 215, 2, ALPHA),
		    new FieldSpec("FM37A-CLERK-NUM", 217, 4, ALPHA),
		    new FieldSpec("FM37A-ACCT-TYPE-CD", 221, 1, ALPHA),
		    new FieldSpec("FM37A-ONL-REL-STS-CD", 222, 1, ALPHA),
		    new FieldSpec("FM37A-PRFX-ACCT-ID", 223, 20, ALPHA),
		    new FieldSpec("FM37A-CB-RATE-AMT", 243, 6, PACKED_DECIMAL, 2),
		    new FieldSpec("FM37A-FILLER-3", 249, 7, ALPHA)
		);
	
	public static final List<FieldSpec> FM37B = List.of(
		    new FieldSpec("FM37B-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
		    new FieldSpec("FM37B-SER-NUM-JULDT-CC", 4, 2, NUMERIC_TEXT),
		    new FieldSpec("FM37B-SER-NUM-JULDT-YY", 6, 2, NUMERIC_TEXT),
		    new FieldSpec("FM37B-SER-NUM-JULDT-DDD", 8, 3, NUMERIC_TEXT),
		    new FieldSpec("FM37B-SER-NUM-JULIAN-DATE-9", 4, 7, NUMERIC_TEXT),
		    new FieldSpec("FM37B-SER-NUM-SEQUENCE", 11, 5, NUMERIC_TEXT),
		    new FieldSpec("FM37B-SER-NUM-SUFFIX", 16, 2, NUMERIC_TEXT),
		    new FieldSpec("FM37B-FILLER-1", 18, 2, ALPHA),
		    new FieldSpec("FM37B-TRANS-ID", 20, 2, ALPHA),
		    new FieldSpec("FM37B-REC-TYPE", 22, 2, ALPHA),
		    new FieldSpec("FM37B-SEQ-NUM", 24, 2, NUMERIC_TEXT),
		    new FieldSpec("FM37B-BATCH-NUM", 26, 14, ALPHA),
		    new FieldSpec("FM37B-BATCH-CREATE-DT-CC", 40, 2, ALPHA),
		    new FieldSpec("FM37B-BATCH-CREATE-DT-YY", 42, 2, ALPHA),
		    new FieldSpec("FM37B-BATCH-CREATE-DT-MM", 44, 2, ALPHA),
		    new FieldSpec("FM37B-BATCH-CREATE-DT-DD", 46, 2, ALPHA),
		    new FieldSpec("FM37B-HOME-AUTH-DEN-DT-CC", 48, 2, ALPHA),
		    new FieldSpec("FM37B-HOME-AUTH-DEN-DT-YY", 50, 2, ALPHA),
		    new FieldSpec("FM37B-HOME-AUTH-DEN-DT-MM", 52, 2, ALPHA),
		    new FieldSpec("FM37B-HOME-AUTH-DEN-DT-DD", 54, 2, ALPHA),
		    new FieldSpec("FM37B-CFA-DISP-DT-CC", 56, 2, ALPHA),
		    new FieldSpec("FM37B-CFA-DISP-DT-YY", 58, 2, ALPHA),
		    new FieldSpec("FM37B-CFA-DISP-DT-MM", 60, 2, ALPHA),
		    new FieldSpec("FM37B-CFA-DISP-DT-DD", 62, 2, ALPHA),
		    new FieldSpec("FM37B-CFA-DEFLT-PMT-DT-CC", 64, 2, ALPHA),
		    new FieldSpec("FM37B-CFA-DEFLT-PMT-DT-YY", 66, 2, ALPHA),
		    new FieldSpec("FM37B-CFA-DEFLT-PMT-DT-MM", 68, 2, ALPHA),
		    new FieldSpec("FM37B-CFA-DEFLT-PMT-DT-DD", 70, 2, ALPHA),
		    new FieldSpec("FM37B-CFA-PRCSS-DT-CC", 72, 2, ALPHA),
		    new FieldSpec("FM37B-CFA-PRCSS-DT-YY", 74, 2, ALPHA),
		    new FieldSpec("FM37B-CFA-PRCSS-DT-MM", 76, 2, ALPHA),
		    new FieldSpec("FM37B-CFA-PRCSS-DT-DD", 78, 2, ALPHA),
		    new FieldSpec("FM37B-ERR-CD-1", 80, 5, ALPHA),
		    new FieldSpec("FM37B-ERR-CD-2", 85, 5, ALPHA),
		    new FieldSpec("FM37B-ERR-CD-3", 90, 5, ALPHA),
		    new FieldSpec("FM37B-ERR-CD-4", 95, 5, ALPHA),
		    new FieldSpec("FM37B-ERR-CD-5", 100, 5, ALPHA),
		    new FieldSpec("FM37B-STATUS-CD", 105, 1, ALPHA),
		    new FieldSpec("FM37B-CFA-STAT-CD", 106, 1, ALPHA),
		    new FieldSpec("FM37B-EDIT-DT-CC", 107, 2, ALPHA),
		    new FieldSpec("FM37B-EDIT-DT-YY", 109, 2, ALPHA),
		    new FieldSpec("FM37B-EDIT-DT-MM", 111, 2, ALPHA),
		    new FieldSpec("FM37B-EDIT-DT-DD", 113, 2, ALPHA),
		    new FieldSpec("FM37B-TYPE-CFA-REIMB", 115, 1, ALPHA),
		    new FieldSpec("FM37B-TYPE-CFA-TRANS", 116, 2, ALPHA),
		    new FieldSpec("FM37B-TRANS-IND", 118, 1, ALPHA),
		    new FieldSpec("FM37B-FILLER-2", 119, 137, ALPHA)
		);
	
	public static final List<FieldSpec> FM39A = List.of(
		    new FieldSpec("FM39A-BATCH-NUM", 1, 14, ALPHA),
		    new FieldSpec("FM39A-FILLER-1", 15, 5, ALPHA),
		    new FieldSpec("FM39A-TRANS-ID", 20, 2, ALPHA),
		    new FieldSpec("FM39A-REC-TYPE", 22, 2, ALPHA),
		    new FieldSpec("FM39A-SEQ-NUM", 24, 2, NUMERIC_TEXT),
		    new FieldSpec("FM39A-CNTL-PLAN-CD", 26, 3, ALPHA),
		    new FieldSpec("FM39A-LOC-PLAN-CD", 29, 3, ALPHA),
		    new FieldSpec("FM39A-TRANS-CNT", 32, 5, PACKED_DECIMAL, 0),
		    new FieldSpec("FM39A-REC-CNT", 37, 5, PACKED_DECIMAL, 0),
		    new FieldSpec("FM39A-TOT-NET-CB-AMT", 42, 7, PACKED_DECIMAL, 2),
		    new FieldSpec("FM39A-TRANS-DT-CC", 49, 2, ALPHA),
		    new FieldSpec("FM39A-TRANS-DT-YY", 51, 2, ALPHA),
		    new FieldSpec("FM39A-TRANS-DT-MM", 53, 2, ALPHA),
		    new FieldSpec("FM39A-TRANS-DT-DD", 55, 2, ALPHA),
		    new FieldSpec("FM39A-AUTH-CNT", 57, 5, PACKED_DECIMAL, 0),
		    new FieldSpec("FM39A-DEN-CNT", 62, 5, PACKED_DECIMAL, 0),
		    new FieldSpec("FM39A-AUTH-TOT-CB-AMOUNT", 67, 7, PACKED_DECIMAL, 2),
		    new FieldSpec("FM39A-DEN-TOT-CB-AMOUNT", 74, 7, PACKED_DECIMAL, 2),
		    new FieldSpec("FM39A-FILLER-2", 81, 175, ALPHA)
		);

}
