package com.its255.schema;

import static com.its255.schema.FieldType.ALPHA;
import static com.its255.schema.FieldType.BINARY;
import static com.its255.schema.FieldType.NUMERIC_TEXT;
import static com.its255.schema.FieldType.PACKED_DECIMAL;

import java.util.List;

public final class DispositionSchemas {
	

    public static final List<FieldSpec> FM21A = List.of(
        new FieldSpec("FM21A-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM21A-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM21A-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM21A-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM21A-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM21A-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM21A-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM21A-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM21A-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM21A-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM21A-PROC-SITE-PLAN-CD", 26, 3, ALPHA),
        new FieldSpec("FM21A-LOC-PLAN-CD", 29, 3, ALPHA),
        new FieldSpec("FM21A-CNTL-PLAN-CD", 32, 3, ALPHA),
        new FieldSpec("FM21A-PROC-SITE-STA-CD", 35, 4, ALPHA),
        new FieldSpec("FM21A-LOC-PLAN-STA-CD", 39, 4, ALPHA),
        new FieldSpec("FM21A-TRANSM-MODE-CD", 43, 1, ALPHA),
        new FieldSpec("FM21A-REL-NUM", 44, 3, ALPHA),
        new FieldSpec("FM21A-CLM-TYPE", 47, 2, ALPHA),
        new FieldSpec("FM21A-DISP-CD", 49, 1, ALPHA),
        new FieldSpec("FM21A-DISP-DT-CC", 50, 2, ALPHA),
        new FieldSpec("FM21A-DISP-DT-YY", 52, 2, ALPHA),
        new FieldSpec("FM21A-DISP-DT-MM", 54, 2, ALPHA),
        new FieldSpec("FM21A-DISP-DT-DD", 56, 2, ALPHA),
        new FieldSpec("FM21A-SCDF-TYPE-CD", 58, 1, ALPHA),
        new FieldSpec("FM21A-PLAN-PAYER-CD", 59, 1, ALPHA),
        new FieldSpec("FM21A-PMT-DISP-CD", 60, 1, ALPHA),
        new FieldSpec("FM21A-ADJUD-STAT-IND", 61, 1, ALPHA),
        new FieldSpec("FM21A-DT-PAID-CC", 62, 2, ALPHA),
        new FieldSpec("FM21A-DT-PAID-YY", 64, 2, ALPHA),
        new FieldSpec("FM21A-DT-PAID-MM", 66, 2, ALPHA),
        new FieldSpec("FM21A-DT-PAID-DD", 68, 2, ALPHA),
        new FieldSpec("FM21A-PMT-RSTRCT-IND", 70, 1, ALPHA),
        new FieldSpec("FM21A-TYPE-BILL", 71, 3, ALPHA),
        new FieldSpec("FM21A-INP-MED", 74, 1, ALPHA),
        new FieldSpec("FM21A-LOC-PLAN-CNTL-NUM", 75, 17, ALPHA),
        new FieldSpec("FM21A-LOC-PLAN-CLM-REF-NUM", 92, 17, ALPHA),
        new FieldSpec("FM21A-PROC-SITE-CNTL-NUM", 109, 17, ALPHA),
        new FieldSpec("FM21A-PREV-TOT-AMT-PAID", 126, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM21A-PREV-DISP-CC", 132, 2, ALPHA),
        new FieldSpec("FM21A-PREV-DISP-YY", 134, 2, ALPHA),
        new FieldSpec("FM21A-PREV-DISP-MM", 136, 2, ALPHA),
        new FieldSpec("FM21A-PREV-DISP-DD", 138, 2, ALPHA),
        new FieldSpec("FM21A-CREATE-DT-CC", 140, 2, ALPHA),
        new FieldSpec("FM21A-CREATE-DT-YY", 142, 2, ALPHA),
        new FieldSpec("FM21A-CREATE-DT-MM", 144, 2, ALPHA),
        new FieldSpec("FM21A-CREATE-DT-DD", 146, 2, ALPHA),
        new FieldSpec("FM21A-TRANS-IND", 148, 1, ALPHA),
        new FieldSpec("FM21A-PLAN-PROF-STND-IND", 149, 1, ALPHA),
        new FieldSpec("FM21A-STAT-CD", 150, 1, ALPHA),
        new FieldSpec("FM21A-ERR-CD-1", 151, 5, ALPHA),
        new FieldSpec("FM21A-ERR-CD-2", 156, 5, ALPHA),
        new FieldSpec("FM21A-ERR-CD-3", 161, 5, ALPHA),
        new FieldSpec("FM21A-ERR-CD-4", 166, 5, ALPHA),
        new FieldSpec("FM21A-ERR-CD-5", 171, 5, ALPHA),
        new FieldSpec("FM21A-EDIT-DT-CC", 176, 2, ALPHA),
        new FieldSpec("FM21A-EDIT-DT-YY", 178, 2, ALPHA),
        new FieldSpec("FM21A-EDIT-DT-MM", 180, 2, ALPHA),
        new FieldSpec("FM21A-EDIT-DT-DD", 182, 2, ALPHA),
        new FieldSpec("FM21A-ADJ-RSN-CD", 184, 2, ALPHA),
        new FieldSpec("FM21A-NET-LIAB-AMT", 186, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM21A-CASH-REFND-IND", 192, 1, ALPHA),
        new FieldSpec("FM21A-CFA-CD", 193, 1, ALPHA),
        new FieldSpec("FM21A-LINE-BUS", 194, 1, ALPHA),
        new FieldSpec("FM21A-RECYC-CTR", 195, 1, NUMERIC_TEXT),
        new FieldSpec("FM21A-PLAN-PROF-ADJ-EDIT-IND", 196, 1, ALPHA),
        new FieldSpec("FM21A-NAT-OOA-CD", 197, 1, ALPHA),
        new FieldSpec("FM21A-PGM-CD", 198, 1, ALPHA),
        new FieldSpec("FM21A-CNTL-PLAN-CFA-ACCT-CD", 199, 2, ALPHA),
        new FieldSpec("FM21A-INVEST-IND", 201, 1, ALPHA),
        new FieldSpec("FM21A-CARVE-OUT-IND", 202, 1, ALPHA),
        new FieldSpec("FM21A-CARVE-OUT-DAY", 203, 3, NUMERIC_TEXT),
        new FieldSpec("FM21A-REF-NUM-LOCAL-PLAN", 206, 3, ALPHA),
        new FieldSpec("FM21A-REF-NUM-JULDT-CC", 209, 2, ALPHA),
        new FieldSpec("FM21A-REF-NUM-JULDT-YY", 211, 2, ALPHA),
        new FieldSpec("FM21A-REF-NUM-JULDT-DDD", 213, 3, ALPHA),
        new FieldSpec("FM21A-REF-NUM-SEQUENCE", 216, 5, ALPHA),
        new FieldSpec("FM21A-REF-NUM-SUFFIX", 221, 2, ALPHA),
        new FieldSpec("FM21A-LOC-PLAN-RCPT-DT-CC", 223, 2, ALPHA),
        new FieldSpec("FM21A-LOC-PLAN-RCPT-DT-YY", 225, 2, ALPHA),
        new FieldSpec("FM21A-LOC-PLAN-RCPT-DT-MM", 227, 2, ALPHA),
        new FieldSpec("FM21A-LOC-PLAN-RCPT-DT-DD", 229, 2, ALPHA),
        new FieldSpec("FM21A-TYPE-DISP", 231, 1, ALPHA),
        new FieldSpec("FM21A-FMT-DB-POST-DT-CC", 232, 2, ALPHA),
        new FieldSpec("FM21A-FMT-DB-POST-DT-YY", 234, 2, ALPHA),
        new FieldSpec("FM21A-FMT-DB-POST-DT-MM", 236, 2, ALPHA),
        new FieldSpec("FM21A-FMT-DB-POST-DT-DD", 238, 2, ALPHA),
        new FieldSpec("FM21A-CFA-BILL-IND", 240, 1, ALPHA),
        new FieldSpec("FM21A-AEA-CD", 241, 1, ALPHA),
        new FieldSpec("FM21A-ACCESS-FEE-CD", 242, 1, ALPHA),
        new FieldSpec("FM21A-RESUB-DF-IND", 243, 1, ALPHA),
        new FieldSpec("FM21A-BCP-PROD-TYPE", 244, 1, ALPHA),
        new FieldSpec("FM21A-PLAN-OWNER-IND", 245, 1, ALPHA),
        new FieldSpec("FM21A-EXCLUDE-PER-USER", 246, 1, ALPHA),
        new FieldSpec("FM21A-EXCLUDE-PER-BLUECD", 247, 1, ALPHA),
        new FieldSpec("FM21A-INTL-CD", 248, 1, ALPHA),
        new FieldSpec("FM21A-STREAM-ADJ-IND", 249, 1, ALPHA),
        new FieldSpec("FM21A-INDEM-CUTBK-IND", 250, 1, ALPHA),
        new FieldSpec("FM21A-ECR-IND", 251, 1, ALPHA),
        new FieldSpec("FM21A-ACCT-TYPE-CD", 252, 1, ALPHA),
        new FieldSpec("FM21A-FMT-CONV-IND", 253, 1, ALPHA),
        new FieldSpec("FM21A-FILLER-1", 254, 2, ALPHA)
        );
    public static final List<FieldSpec> FM22A = List.of(
        new FieldSpec("FM22A-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM22A-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM22A-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM22A-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM22A-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM22A-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM22A-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM22A-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM22A-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM22A-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM22A-BCBS-PROV-NUM", 26, 13, ALPHA),
        new FieldSpec("FM22A-PROV-NAME", 39, 31, ALPHA),
        new FieldSpec("FM22A-PROV-ADDR-LN-1", 70, 25, ALPHA),
        new FieldSpec("FM22A-PROV-CITY", 95, 15, ALPHA),
        new FieldSpec("FM22A-PROV-ST", 110, 2, ALPHA),
        new FieldSpec("FM22A-PROV-ZIP-CD-5", 112, 5, ALPHA),
        new FieldSpec("FM22A-PROV-ZIP-CD-4", 117, 4, ALPHA),
        new FieldSpec("FM22A-FED-TAX-ID-NUM", 121, 9, ALPHA),
        new FieldSpec("FM22A-TYPE-FED-TAX-ID-NUM", 130, 1, ALPHA),
        new FieldSpec("FM22A-CLASS-PROV-CLM", 131, 1, ALPHA),
        new FieldSpec("FM22A-REF-PROV-NUM", 132, 14, ALPHA),
        new FieldSpec("FM22A-PROV-NPI", 146, 10, ALPHA),
        new FieldSpec("FM22A-CUST-PRIMY-NTWK", 156, 4, ALPHA),
        new FieldSpec("FM22A-CUST-SCNDY-NTWK", 160, 4, ALPHA),
        new FieldSpec("FM22A-BOID", 164, 4, ALPHA),
        new FieldSpec("FM22A-FILLER-1", 168, 88, ALPHA)
    );
    public static final List<FieldSpec> FM22B = List.of(
        new FieldSpec("FM22B-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM22B-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM22B-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM22B-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM22B-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM22B-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM22B-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM22B-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM22B-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM22B-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM22B-PAT-CNTL-NUM", 26, 20, ALPHA),
        new FieldSpec("FM22B-PAT-LAST-NAME", 46, 20, ALPHA),
        new FieldSpec("FM22B-PAT-FIRST-NAME", 66, 10, ALPHA),
        new FieldSpec("FM22B-PAT-MID-INIT", 76, 1, ALPHA),
        new FieldSpec("FM22B-PAT-BRT-DT-CC", 77, 2, ALPHA),
        new FieldSpec("FM22B-PAT-BRT-DT-YY", 79, 2, ALPHA),
        new FieldSpec("FM22B-PAT-BRT-DT-MM", 81, 2, ALPHA),
        new FieldSpec("FM22B-PAT-BRT-DT-DD", 83, 2, ALPHA),
        new FieldSpec("FM22B-PAT-SEX", 85, 1, ALPHA),
        new FieldSpec("FM22B-PAT-REL-SUB", 86, 2, ALPHA),
        new FieldSpec("FM22B-CORR-PRI-PAYER-NM", 88, 16, ALPHA),
        new FieldSpec("FM22B-OTH-SUB-LAST-NM", 104, 20, ALPHA),
        new FieldSpec("FM22B-OTH-SUB-MDL-INIT", 124, 1, ALPHA),
        new FieldSpec("FM22B-OTH-SUB-FIRST-NM", 125, 10, ALPHA),
        new FieldSpec("FM22B-OTH-SUB-ID-NUM", 135, 17, ALPHA),
        new FieldSpec("FM22B-FILLER-1", 152, 104, ALPHA)
    );
    public static final List<FieldSpec> FM22C = List.of(
        new FieldSpec("FM22C-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM22C-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM22C-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM22C-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM22C-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM22C-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM22C-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM22C-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM22C-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM22C-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM22C-SUB-ID-ACTUAL-PFX-1-3", 26, 3, ALPHA),
        new FieldSpec("FM22C-SUB-ID-ACTUAL-SUFX-4-17", 29, 14, ALPHA),
        new FieldSpec("FM22C-SUB-ID-INP-PFX-1-3", 43, 3, ALPHA),
        new FieldSpec("FM22C-SUB-ID-INP-SUFX-4-17", 46, 14, ALPHA),
        new FieldSpec("FM22C-SUB-GRP-NUM", 60, 9, ALPHA),
        new FieldSpec("FM22C-SUB-LAST-NAME", 69, 20, ALPHA),
        new FieldSpec("FM22C-SUB-FIRST-NAME", 89, 10, ALPHA),
        new FieldSpec("FM22C-SUB-MID-INIT", 99, 1, ALPHA),
        new FieldSpec("FM22C-SUB-ADDR-LN-1", 100, 25, ALPHA),
        new FieldSpec("FM22C-SUB-ADDR-LN-2", 125, 25, ALPHA),
        new FieldSpec("FM22C-SUB-CITY", 150, 15, ALPHA),
        new FieldSpec("FM22C-SUB-ST", 165, 2, ALPHA),
        new FieldSpec("FM22C-SUB-ZIP-CD-5", 167, 5, ALPHA),
        new FieldSpec("FM22C-SUB-ZIP-CD-4", 172, 4, ALPHA),
        new FieldSpec("FM22C-ASO-IND", 176, 1, ALPHA),
        new FieldSpec("FM22C-PRFX-ACCT-ID-IND", 177, 1, ALPHA),
        new FieldSpec("FM22C-PRFX-ACCT-ID", 178, 20, ALPHA),
        new FieldSpec("FM22C-FILLER-1", 198, 58, ALPHA)
    );
    public static final List<FieldSpec> FM22E = List.of(
        new FieldSpec("FM22E-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM22E-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM22E-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM22E-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM22E-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM22E-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM22E-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM22E-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM22E-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM22E-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM22E-REP-PAYEE-STR-ADDR", 26, 25, ALPHA),
        new FieldSpec("FM22E-REP-PAYEE-CITY", 51, 15, ALPHA),
        new FieldSpec("FM22E-REP-PAYEE-ST", 66, 2, ALPHA),
        new FieldSpec("FM22E-REP-PAYEE-ZIP-CD-5", 68, 5, ALPHA),
        new FieldSpec("FM22E-REP-PAYEE-ZIP-CD-4", 73, 4, ALPHA),
        new FieldSpec("FM22E-REP-PAYEE-NAME", 77, 31, ALPHA),
        new FieldSpec("FM22E-FILLER-1", 108, 148, ALPHA)
    );
    public static final List<FieldSpec> FM22F = List.of(
        new FieldSpec("FM22F-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM22F-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM22F-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM22F-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM22F-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM22F-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM22F-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM22F-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM22F-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM22F-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM22F-MED-PROV-NUM", 26, 13, ALPHA),
        new FieldSpec("FM22F-ADM-DT-CC", 39, 2, ALPHA),
        new FieldSpec("FM22F-ADM-DT-YY", 41, 2, ALPHA),
        new FieldSpec("FM22F-ADM-DT-MM", 43, 2, ALPHA),
        new FieldSpec("FM22F-ADM-DT-DD", 45, 2, ALPHA),
        new FieldSpec("FM22F-STMT-COV-FROM-DT-CC", 47, 2, ALPHA),
        new FieldSpec("FM22F-STMT-COV-FROM-DT-YY", 49, 2, ALPHA),
        new FieldSpec("FM22F-STMT-COV-FROM-DT-MM", 51, 2, ALPHA),
        new FieldSpec("FM22F-STMT-COV-FROM-DT-DD", 53, 2, ALPHA),
        new FieldSpec("FM22F-STMT-COV-TO-DT-CC", 55, 2, ALPHA),
        new FieldSpec("FM22F-STMT-COV-TO-DT-YY", 57, 2, ALPHA),
        new FieldSpec("FM22F-STMT-COV-TO-DT-MM", 59, 2, ALPHA),
        new FieldSpec("FM22F-STMT-COV-TO-DT-DD", 61, 2, ALPHA),
        new FieldSpec("FM22F-POS-IND", 63, 1, ALPHA),
        new FieldSpec("FM22F-PAYER-NM", 64, 50, ALPHA),
        new FieldSpec("FM22F-PAYER-ADDR", 114, 30, ALPHA),
        new FieldSpec("FM22F-PAYER-CITY", 144, 15, ALPHA),
        new FieldSpec("FM22F-PAYER-ST", 159, 2, ALPHA),
        new FieldSpec("FM22F-PAYER-ZIP-CD", 161, 9, ALPHA),
        new FieldSpec("FM22F-PAYER-TAX-ID", 170, 9, ALPHA),
        new FieldSpec("FM22F-FILLER-1", 179, 77, ALPHA)
    );
    public static final List<FieldSpec> FM22G = List.of(
        new FieldSpec("FM22G-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM22G-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM22G-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM22G-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM22G-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM22G-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM22G-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM22G-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM22G-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM22G-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM22G-POS-IND", 26, 1, ALPHA),
        new FieldSpec("FM22G-PERF-PROV-NPI-CLM", 27, 10, ALPHA),
        new FieldSpec("FM22G-PAYER-NM", 37, 50, ALPHA),
        new FieldSpec("FM22G-PAYER-ADDR", 87, 30, ALPHA),
        new FieldSpec("FM22G-PAYER-CITY", 117, 15, ALPHA),
        new FieldSpec("FM22G-PAYER-ST", 132, 2, ALPHA),
        new FieldSpec("FM22G-PAYER-ZIP-CD", 134, 9, ALPHA),
        new FieldSpec("FM22G-PAYER-TAX-ID", 143, 9, ALPHA),
        new FieldSpec("FM22G-FILLER-1", 152, 104, ALPHA)
    );
    public static final List<FieldSpec> FM22H = List.of(
        new FieldSpec("FM22H-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM22H-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM22H-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM22H-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM22H-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM22H-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM22H-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM22H-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM22H-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM22H-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM22H-FILLER-1", 26, 230, ALPHA)
    );
    public static final List<FieldSpec> FM23A = List.of(
        new FieldSpec("FM23A-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM23A-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM23A-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM23A-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM23A-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM23A-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM23A-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM23A-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM23A-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM23A-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM23A-DF-MSG-CD-CLM-1", 26, 4, ALPHA),
        new FieldSpec("FM23A-DF-MSG-CD-CLM-2", 30, 4, ALPHA),
        new FieldSpec("FM23A-DF-MSG-CD-CLM-3", 34, 4, ALPHA),
        new FieldSpec("FM23A-DF-MSG-CD-CLM-4", 38, 4, ALPHA),
        new FieldSpec("FM23A-DF-MSG-CD-CLM-5", 42, 4, ALPHA),
        new FieldSpec("FM23A-TOT-BNFIT-MGMT-RED-DAY", 46, 3, NUMERIC_TEXT),
        new FieldSpec("FM23A-TOT-DED-AMT", 49, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-CO-INS-AMT", 55, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-CO-PAY-AMT", 61, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-AMT-PAID-OTH-CARR", 67, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-CHRG-ALL-SERV", 73, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-COV-CHRG", 79, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-NON-COV-CHRG", 85, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-AMT-APPV-PMT", 91, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-PAT-LIAB-AMT", 97, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-PAT-AMT-PAID", 103, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-PMT-RED-RSN-CD-1", 109, 2, ALPHA),
        new FieldSpec("FM23A-TOT-PMT-RED-AMT-1", 111, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-PMT-RED-RSN-CD-2", 117, 2, ALPHA),
        new FieldSpec("FM23A-TOT-PMT-RED-AMT-2", 119, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-PMT-RED-RSN-CD-3", 125, 2, ALPHA),
        new FieldSpec("FM23A-TOT-PMT-RED-AMT-3", 127, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-PMT-RED-RSN-CD-4", 133, 2, ALPHA),
        new FieldSpec("FM23A-TOT-PMT-RED-AMT-4", 135, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-PMT-RED-RSN-CD-5", 141, 2, ALPHA),
        new FieldSpec("FM23A-TOT-PMT-RED-AMT-5", 143, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-SUPPL-PMT-AMT-1-CLM", 149, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-SUPPL-PMT-AMT-2-CLM", 155, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-CASE-MGMT-IND", 161, 1, ALPHA),
        new FieldSpec("FM23A-TOT-PMT-RED-RSN-CD-6", 162, 2, ALPHA),
        new FieldSpec("FM23A-TOT-PMT-RED-AMT-6", 164, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-PMT-RED-RSN-CD-7", 170, 2, ALPHA),
        new FieldSpec("FM23A-TOT-PMT-RED-AMT-7", 172, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-PMT-RED-RSN-CD-8", 178, 2, ALPHA),
        new FieldSpec("FM23A-TOT-PMT-RED-AMT-8", 180, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-PMT-RED-RSN-CD-9", 186, 2, ALPHA),
        new FieldSpec("FM23A-TOT-PMT-RED-AMT-9", 188, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-TOT-PMT-RED-RSN-CD-10", 194, 2, ALPHA),
        new FieldSpec("FM23A-TOT-PMT-RED-AMT-10", 196, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-PRIM-IND", 202, 1, ALPHA),
        new FieldSpec("FM23A-COB-CALC-MTD", 203, 3, ALPHA),
        new FieldSpec("FM23A-COB-SAV-AMT", 206, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-SEC-PAYOR-PRC-QUAL", 212, 1, ALPHA),
        new FieldSpec("FM23A-INC-CALC-DISC-AMT", 213, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-MPPQ-CD-ASGN", 219, 1, ALPHA),
        new FieldSpec("FM23A-MPPQ-CD-UNASGN", 220, 1, ALPHA),
        new FieldSpec("FM23A-MED-ASGNMT-IND", 221, 1, ALPHA),
        new FieldSpec("FM23A-INCL-MAX-SUPP-AMT", 222, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23A-EST-IND", 228, 1, ALPHA),
        new FieldSpec("FM23A-DEFLT-CLM-RSLTN-IND", 229, 1, ALPHA),
        new FieldSpec("FM23A-INIT-TRANSM-MODE-CD", 230, 1, ALPHA),
        new FieldSpec("FM23A-COV-EXP-DATE-CC", 231, 2, ALPHA),
        new FieldSpec("FM23A-COV-EXP-DATE-YY", 233, 2, ALPHA),
        new FieldSpec("FM23A-COV-EXP-DATE-MM", 235, 2, ALPHA),
        new FieldSpec("FM23A-COV-EXP-DATE-DD", 237, 2, ALPHA),
        new FieldSpec("FM23A-EXCESS-DAYS", 239, 3, NUMERIC_TEXT),
        new FieldSpec("FM23A-FILLER-1", 242, 14, ALPHA)
    );
    public static final List<FieldSpec> FM23C = List.of(
        new FieldSpec("FM23C-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM23C-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM23C-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM23C-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM23C-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM23C-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM23C-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM23C-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM23C-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM23C-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM23C-PRC-MTD-CLM", 26, 2, ALPHA),
        new FieldSpec("FM23C-RULE-NUM-PRIM-CLM-1-3", 28, 3, ALPHA),
        new FieldSpec("FM23C-RULE-NUM-PRIM-CLM-4-6", 31, 3, ALPHA),
        new FieldSpec("FM23C-RULE-NUM-SEC-CLM-1-3", 34, 3, ALPHA),
        new FieldSpec("FM23C-RULE-NUM-SEC-CLM-4-6", 37, 3, ALPHA),
        new FieldSpec("FM23C-PCT-FCTR-CLM", 40, 3, PACKED_DECIMAL, 2),
        new FieldSpec("FM23C-TOT-COV-ACCOM-CHRG", 43, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23C-TOT-COV-ANC-CHRG", 49, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23C-TOT-DAYS-APPV-PMT", 55, 3, NUMERIC_TEXT),
        new FieldSpec("FM23C-ACCESS-FEE-PCT", 58, 3, PACKED_DECIMAL, 2),
        new FieldSpec("FM23C-ACCESS-FEE-AMT", 61, 5, PACKED_DECIMAL, 2),
        new FieldSpec("FM23C-ADMIN-EXP-ALLW", 66, 5, PACKED_DECIMAL, 2),
        new FieldSpec("FM23C-CLM-LIAB-AMT", 71, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23C-ALLW-PREPRC-AMT", 77, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23C-OUT-NETW-SAV-PEN-AMT", 83, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23C-NON-COV-DAYS", 89, 4, NUMERIC_TEXT),
        new FieldSpec("FM23C-LNG-STAY", 93, 3, NUMERIC_TEXT),
        new FieldSpec("FM23C-TOT-PVT-RM-NONCOV-AMT", 96, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23C-NON-STD-ACC-FEE-PCT", 102, 3, PACKED_DECIMAL, 2),
        new FieldSpec("FM23C-NON-STD-ACC-FEE-PCT-X", 102, 3, ALPHA), 
        new FieldSpec("FM23C-FEE-SRC-CD", 105, 1, ALPHA),
        new FieldSpec("FM23C-FILLER-1", 106, 150, ALPHA)
    );
    public static final List<FieldSpec> FM23D = List.of(
        new FieldSpec("FM23D-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM23D-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM23D-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM23D-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM23D-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM23D-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM23D-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM23D-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM23D-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM23D-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM23D-TOT-COV-SERV-CHRG", 26, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23D-INCUR-DT-CC", 32, 2, ALPHA),
        new FieldSpec("FM23D-INCUR-DT-YY", 34, 2, ALPHA),
        new FieldSpec("FM23D-INCUR-DT-MM", 36, 2, ALPHA),
        new FieldSpec("FM23D-INCUR-DT-DD", 38, 2, ALPHA),
        new FieldSpec("FM23D-ACCESS-FEE-PCT", 40, 3, PACKED_DECIMAL, 2),
        new FieldSpec("FM23D-ACCESS-FEE-AMT", 43, 5, PACKED_DECIMAL, 2),
        new FieldSpec("FM23D-ADMIN-EXP-ALLW", 48, 5, PACKED_DECIMAL, 2),
        new FieldSpec("FM23D-CLM-LIAB-AMT", 53, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23D-ALLW-PREPRC-AMT", 59, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23D-OUT-NETW-SAV-PEN-AMT", 65, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM23D-PERF-PROV-POS-IND-CLM", 71, 1, ALPHA),
        new FieldSpec("FM23D-PREDETRMN-BNFT-ID-CLM", 72, 30, ALPHA),
        new FieldSpec("FM23D-NON-STD-ACC-FEE-PCT", 102, 3, PACKED_DECIMAL, 2),
        new FieldSpec("FM23D-NON-STD-ACC-FEE-PCT-X", 102, 3, ALPHA), 
        new FieldSpec("FM23D-FEE-SRC-CD", 105, 1, ALPHA),
        new FieldSpec("FM23D-FILLER-1", 106, 150, ALPHA)
    );
    public static final List<FieldSpec> FM24A = List.of(
        new FieldSpec("FM24A-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM24A-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM24A-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM24A-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM24A-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM24A-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM24A-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM24A-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM24A-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM24A-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM24A-DF-MSG-CD-LN", 26, 4, ALPHA),
        new FieldSpec("FM24A-SERV-CHRG", 30, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-COV-CHRG", 36, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-NON-COV-CHRG", 42, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-NUM-SERV", 48, 4, NUMERIC_TEXT),
        new FieldSpec("FM24A-PAT-LIAB-AMT", 52, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-BNFT-MGMT-RED-DAYS", 58, 3, NUMERIC_TEXT),
        new FieldSpec("FM24A-DED-AMT", 61, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-CO-INS-AMT", 67, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-CO-PAY-AMT", 73, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-AMT-PAID-OTH-CARR", 79, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-AMT-EXCD-MAX", 85, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-AMT-APPV-PMT", 91, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-PMT-RED-RSN-CD-1", 97, 2, ALPHA),
        new FieldSpec("FM24A-PMT-RED-AMT-1", 99, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-PMT-RED-RSN-CD-2", 105, 2, ALPHA),
        new FieldSpec("FM24A-PMT-RED-AMT-2", 107, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-PMT-RED-RSN-CD-3", 113, 2, ALPHA),
        new FieldSpec("FM24A-PMT-RED-AMT-3", 115, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-PMT-RED-RSN-CD-4", 121, 2, ALPHA),
        new FieldSpec("FM24A-PMT-RED-AMT-4", 123, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-PMT-RED-RSN-CD-5", 129, 2, ALPHA),
        new FieldSpec("FM24A-PMT-RED-AMT-5", 131, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-PCT-FCTR-LN", 137, 3, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-ADDL-LN-BUS-IND", 140, 1, ALPHA),
        new FieldSpec("FM24A-PRC-MTD-LN", 141, 2, ALPHA),
        new FieldSpec("FM24A-RULE-NUM-LN-1-3", 143, 3, ALPHA),
        new FieldSpec("FM24A-RULE-NUM-LN-4-6", 146, 3, ALPHA),
        new FieldSpec("FM24A-SUPPL-PMT-AMT-1-LN", 149, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-SUPPL-PMT-AMT-2-LN", 155, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-PMT-RED-RSN-CD-6", 161, 2, ALPHA),
        new FieldSpec("FM24A-PMT-RED-AMT-6", 163, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-PMT-RED-RSN-CD-7", 169, 2, ALPHA),
        new FieldSpec("FM24A-PMT-RED-AMT-7", 171, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-PMT-RED-RSN-CD-8", 177, 2, ALPHA),
        new FieldSpec("FM24A-PMT-RED-AMT-8", 179, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-PMT-RED-RSN-CD-9", 185, 2, ALPHA),
        new FieldSpec("FM24A-PMT-RED-AMT-9", 187, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-PMT-RED-RSN-CD-10", 193, 2, ALPHA),
        new FieldSpec("FM24A-PMT-RED-AMT-10", 195, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-CALC-DISC-AMT", 201, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-PERF-PROV-NPI-LN", 207, 10, ALPHA),
        new FieldSpec("FM24A-MAX-SUPP-AMT", 217, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24A-INCL-GROUPING-NBR", 223, 2, ALPHA),
        new FieldSpec("FM24A-FILLER-1", 225, 31, ALPHA)
    );
    public static final List<FieldSpec> FM24B = List.of(
        new FieldSpec("FM24B-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM24B-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM24B-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM24B-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM24B-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM24B-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM24B-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM24B-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM24B-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM24B-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM24B-DAYS-APPV-PMT", 26, 3, NUMERIC_TEXT),
        new FieldSpec("FM24B-REV-CD", 29, 4, NUMERIC_TEXT),
        new FieldSpec("FM24B-ACCOM-RATE", 33, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24B-CAP-IND", 39, 1, ALPHA),
        new FieldSpec("FM24B-LOC-PLAN-REF-NUM", 40, 25, ALPHA),
        new FieldSpec("FM24B-POS-PRC-LEV-IND", 65, 1, ALPHA),
        new FieldSpec("FM24B-PREATH-PRECRT-STAT-IND", 66, 1, ALPHA),
        new FieldSpec("FM24B-REF-STAT-IND", 67, 1, ALPHA),
        new FieldSpec("FM24B-REF-PCP-IND", 68, 2, ALPHA),
        new FieldSpec("FM24B-REVIEW-DETER-COND-CD", 70, 2, ALPHA),
        new FieldSpec("FM24B-CNTL-PLAN-AUTH-NUM", 72, 25, ALPHA),
        new FieldSpec("FM24B-CNTL-PLAN-REF-NUM", 97, 25, ALPHA),
        new FieldSpec("FM24B-NON-COV-DAYS", 122, 4, NUMERIC_TEXT),
        new FieldSpec("FM24B-HCPCS-PROC-CD", 126, 5, ALPHA),
        new FieldSpec("FM24B-HCPCS-PROC-CD-MOD-1", 131, 2, ALPHA),
        new FieldSpec("FM24B-HCPCS-PROC-CD-MOD-2", 133, 2, ALPHA),
        new FieldSpec("FM24B-PVT-RM-NONCOV-AMT", 135, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24B-FILLER-1", 141, 115, ALPHA)
    );
    public static final List<FieldSpec> FM24C = List.of(
        new FieldSpec("FM24C-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM24C-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM24C-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM24C-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM24C-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM24C-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM24C-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM24C-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM24C-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM24C-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM24C-TYPE-SERV", 26, 3, ALPHA),
        new FieldSpec("FM24C-DT-SERV-START-CC", 29, 2, ALPHA),
        new FieldSpec("FM24C-DT-SERV-START-YY", 31, 2, ALPHA),
        new FieldSpec("FM24C-DT-SERV-START-MM", 33, 2, ALPHA),
        new FieldSpec("FM24C-DT-SERV-START-DD", 35, 2, ALPHA),
        new FieldSpec("FM24C-DT-SERV-END-CC", 37, 2, ALPHA),
        new FieldSpec("FM24C-DT-SERV-END-YY", 39, 2, ALPHA),
        new FieldSpec("FM24C-DT-SERV-END-MM", 41, 2, ALPHA),
        new FieldSpec("FM24C-DT-SERV-END-DD", 43, 2, ALPHA),
        new FieldSpec("FM24C-HCPCS-PROC-CD", 45, 5, ALPHA),
        new FieldSpec("FM24C-HCPCS-PROC-CD-MOD-1", 50, 2, ALPHA),
        new FieldSpec("FM24C-HCPCS-PROC-CD-MOD-2", 52, 2, ALPHA),
        new FieldSpec("FM24C-CAP-IND", 54, 1, ALPHA),
        new FieldSpec("FM24C-LOC-PLAN-REF-NUM", 55, 25, ALPHA),
        new FieldSpec("FM24C-POS-PRC-LEV-IND", 80, 1, ALPHA),
        new FieldSpec("FM24C-PREATH-PRECRT-STAT-IND", 81, 1, ALPHA),
        new FieldSpec("FM24C-REF-STAT-IND", 82, 1, ALPHA),
        new FieldSpec("FM24C-PERF-PCP-IND", 83, 1, ALPHA),
        new FieldSpec("FM24C-REF-PCP-IND", 84, 2, ALPHA),
        new FieldSpec("FM24C-REVIEW-DETER-COND-CD", 86, 2, ALPHA),
        new FieldSpec("FM24C-PERF-PROV-POS-IND-LN", 88, 1, ALPHA),
        new FieldSpec("FM24C-CNTL-PLAN-AUTH-NUM", 89, 25, ALPHA),
        new FieldSpec("FM24C-CNTL-PLAN-REF-NUM", 114, 25, ALPHA),
        new FieldSpec("FM24C-CLASS-PROV-LN", 139, 1, ALPHA),
        new FieldSpec("FM24C-PREDETRMN-BNFT-IND", 140, 1, ALPHA),
        new FieldSpec("FM24C-PREDETRMN-BNFT-ID-LN", 141, 30, ALPHA),
        new FieldSpec("FM24C-PREDETRMN-AMT", 171, 6, PACKED_DECIMAL, 2),
        new FieldSpec("FM24C-FILLER-1", 177, 79, ALPHA)
    );
    public static final List<FieldSpec> FM24D = List.of(
        new FieldSpec("FM24D-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM24D-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM24D-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM24D-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM24D-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM24D-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM24D-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM24D-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM24D-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM24D-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM24D-HEALTH-POLICY-ID-1", 26, 15, ALPHA),
        new FieldSpec("FM24D-HEALTH-POLICY-ID-2", 41, 15, ALPHA),
        new FieldSpec("FM24D-HEALTH-POLICY-ID-3", 56, 15, ALPHA),
        new FieldSpec("FM24D-HEALTH-POLICY-ID-4", 71, 15, ALPHA),
        new FieldSpec("FM24D-HEALTH-POLICY-ID-5", 86, 15, ALPHA),
        new FieldSpec("FM24D-FILLER-1", 101, 155, ALPHA)
    );
    public static final List<FieldSpec> FM28A = List.of(
        new FieldSpec("FM28A-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM28A-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM28A-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM28A-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM28A-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM28A-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM28A-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM28A-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM28A-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM28A-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM28A-SPEC-NOTE-TRNSM-IND", 26, 1, ALPHA),
        new FieldSpec("FM28A-SPEC-NOTE-CD", 27, 5, ALPHA),
        new FieldSpec("FM28A-SPEC-NOTE-DATA", 32, 215, ALPHA),
        new FieldSpec("FM28A-FILLER-1", 247, 9, ALPHA)
    );
    public static final List<FieldSpec> FM29A = List.of(
        new FieldSpec("FM29A-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
        new FieldSpec("FM29A-SER-NUM-JULDT-CC", 4, 2, ALPHA),
        new FieldSpec("FM29A-SER-NUM-JULDT-YY", 6, 2, ALPHA),
        new FieldSpec("FM29A-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
        new FieldSpec("FM29A-SER-NUM-SEQUENCE", 11, 5, ALPHA),
        new FieldSpec("FM29A-SER-NUM-SUFFIX", 16, 2, ALPHA),
        new FieldSpec("FM29A-TRANS-ID", 18, 2, ALPHA),
        new FieldSpec("FM29A-TRANS-QUAL", 20, 2, ALPHA),
        new FieldSpec("FM29A-REC-TYPE", 22, 2, ALPHA),
        new FieldSpec("FM29A-SEQ-NUM", 24, 2, BINARY),
        new FieldSpec("FM29A-CLERK-NUM", 26, 4, ALPHA),
        new FieldSpec("FM29A-ONL-DT-LAST-ACT-CC", 30, 2, ALPHA),
        new FieldSpec("FM29A-ONL-DT-LAST-ACT-YY", 32, 2, ALPHA),
        new FieldSpec("FM29A-ONL-DT-LAST-ACT-MM", 34, 2, ALPHA),
        new FieldSpec("FM29A-ONL-DT-LAST-ACT-DD", 36, 2, ALPHA),
        new FieldSpec("FM29A-ONL-TIME-LAST-ACT-HH", 38, 2, ALPHA),
        new FieldSpec("FM29A-ONL-TIME-LAST-ACT-MM", 40, 2, ALPHA),
        new FieldSpec("FM29A-ONL-TIME-LAST-ACT-SS", 42, 2, ALPHA),
        new FieldSpec("FM29A-CHK-VCHR-NUM", 44, 10, ALPHA),
        new FieldSpec("FM29A-CHK-DT-CC", 54, 2, ALPHA),
        new FieldSpec("FM29A-CHK-DT-YY", 56, 2, ALPHA),
        new FieldSpec("FM29A-CHK-DT-MM", 58, 2, ALPHA),
        new FieldSpec("FM29A-CHK-DT-DD", 60, 2, ALPHA),
        new FieldSpec("FM29A-BANK-ACCT-NUM", 62, 15, ALPHA),
        new FieldSpec("FM29A-PHY-REC-CNT", 77, 4, NUMERIC_TEXT),
        new FieldSpec("FM29A-REC-TYPE-2X-CNT", 81, 2, NUMERIC_TEXT),
        new FieldSpec("FM29A-REC-TYPE-3X-CNT", 83, 2, NUMERIC_TEXT),
        new FieldSpec("FM29A-REC-TYPE-4A-CNT", 85, 4, NUMERIC_TEXT),
        new FieldSpec("FM29A-REC-TYPE-4B-CNT", 89, 4, NUMERIC_TEXT),
        new FieldSpec("FM29A-REC-TYPE-4C-CNT", 93, 4, NUMERIC_TEXT),
        new FieldSpec("FM29A-REC-TYPE-4D-CNT", 97, 4, NUMERIC_TEXT),
        new FieldSpec("FM29A-REC-TYPE-4X-CNT", 101, 4, NUMERIC_TEXT),
        new FieldSpec("FM29A-REC-TYPE-8X-CNT", 105, 4, NUMERIC_TEXT),
        new FieldSpec("FM29A-SYS-CRT-CD", 109, 1, ALPHA),
        new FieldSpec("FM29A-SYS-UPDT-CD", 110, 1, ALPHA),
        new FieldSpec("FM29A-BLUE2-USER-ID", 111, 40, ALPHA),
        new FieldSpec("FM29A-ADJ-RCPT-DT-CC", 151, 2, ALPHA),
        new FieldSpec("FM29A-ADJ-RCPT-DT-YY", 153, 2, ALPHA),
        new FieldSpec("FM29A-ADJ-RCPT-DT-MM", 155, 2, ALPHA),
        new FieldSpec("FM29A-ADJ-RCPT-DT-DD", 157, 2, ALPHA),
        new FieldSpec("FM29A-FILLER-1", 159, 97, ALPHA)
    );
	

}
