package com.its255.schema;

import static com.its255.schema.FieldType.ALPHA;
import static com.its255.schema.FieldType.BINARY;
import static com.its255.schema.FieldType.NUMERIC_TEXT;
import static com.its255.schema.FieldType.PACKED_DECIMAL;

import java.util.List;

public final class SFProfessionalSchemas {
	
	   
    public static final List<FieldSpec> FM1A5 = List.of(
        new FieldSpec("FM1A5-SER-NUM-LOCAL-PLAN",        1,   3,  ALPHA),
        new FieldSpec("FM1A5-SER-NUM-JULDT-CC",          4,   2,  ALPHA),
        new FieldSpec("FM1A5-SER-NUM-JULDT-YY",          6,   2,  ALPHA),
        new FieldSpec("FM1A5-SER-NUM-JULDT-DDD",         8,   3,  ALPHA),
        new FieldSpec("FM1A5-SER-NUM-SEQUENCE",         11,   5,  ALPHA),
        new FieldSpec("FM1A5-SER-NUM-SUFFIX",           16,   2,  ALPHA),
        new FieldSpec("FM1A5-TRANS-ID",                 18,   2,  ALPHA),
        new FieldSpec("FM1A5-TRANS-QUAL",               20,   2,  ALPHA),
        new FieldSpec("FM1A5-REC-TYPE",                 22,   2,  ALPHA),  
        new FieldSpec("FM1A5-SEQ-NUM",                  24,   2,  BINARY),
        new FieldSpec("FM1A5-CLM-TYPE",                  26,   2,  ALPHA),
        new FieldSpec("FM1A5-LOC-PLAN-CD",               28,   3,  ALPHA),
        new FieldSpec("FM1A5-LOC-PLAN-STA-CD",           31,   4,  ALPHA),
        new FieldSpec("FM1A5-PROC-SITE-PLAN-CD",         35,   3,  ALPHA),
        new FieldSpec("FM1A5-PROC-SITE-STA-CD",          38,   4,  ALPHA),
        new FieldSpec("FM1A5-CNTL-PLAN-CD",              42,   3,  ALPHA),
        new FieldSpec("FM1A5-TRANSM-MODE-CD",            45,   1,  ALPHA),
        new FieldSpec("FM1A5-PLAN-PAYER-CD",             46,   1,  ALPHA),
        new FieldSpec("FM1A5-PMT-DISP-CD",               47,   1,  ALPHA),
        new FieldSpec("FM1A5-LOC-PLAN-CNTL-NUM",         48,  17,  ALPHA),
        new FieldSpec("FM1A5-PROC-SITE-CNTL-NUM",        65,  17,  ALPHA),
        new FieldSpec("FM1A5-LOC-PLAN-CLM-REF-NUM",      82,  17,  ALPHA),
        new FieldSpec("FM1A5-REF-NUM-LOCAL-PLAN",        99,   3,  ALPHA),
        new FieldSpec("FM1A5-REF-NUM-JULDT-CC",         102,   2,  ALPHA),
        new FieldSpec("FM1A5-REF-NUM-JULDT-YY",         104,   2,  ALPHA),
        new FieldSpec("FM1A5-REF-NUM-JULDT-DDD",        106,   3,  ALPHA),
        new FieldSpec("FM1A5-REF-NUM-SEQUENCE",         109,   5,  ALPHA),
        new FieldSpec("FM1A5-REF-NUM-SUFFIX",           114,   2,  ALPHA),
        new FieldSpec("FM1A5-INP-MED",                  116,   1,  ALPHA),
        new FieldSpec("FM1A5-REL-NUM",                  117,   3,  ALPHA),
        new FieldSpec("FM1A5-LOC-PLAN-RCPT-DT-CC",      120,   2,  ALPHA),
        new FieldSpec("FM1A5-LOC-PLAN-RCPT-DT-YY",      122,   2,  ALPHA),
        new FieldSpec("FM1A5-LOC-PLAN-RCPT-DT-MM",      124,   2,  ALPHA),
        new FieldSpec("FM1A5-LOC-PLAN-RCPT-DT-DD",      126,   2,  ALPHA),
        new FieldSpec("FM1A5-EDIT-DT-CC",               128,   2,  ALPHA),
        new FieldSpec("FM1A5-EDIT-DT-YY",               130,   2,  ALPHA),
        new FieldSpec("FM1A5-EDIT-DT-MM",               132,   2,  ALPHA),
        new FieldSpec("FM1A5-EDIT-DT-DD",               134,   2,  ALPHA),
        new FieldSpec("FM1A5-PGM-CD",                   136,   1,  ALPHA),
        new FieldSpec("FM1A5-ONL-DT-LAST-ACT-CC",       137,   2,  ALPHA),
        new FieldSpec("FM1A5-ONL-DT-LAST-ACT-YY",       139,   2,  ALPHA),
        new FieldSpec("FM1A5-ONL-DT-LAST-ACT-MM",       141,   2,  ALPHA),
        new FieldSpec("FM1A5-ONL-DT-LAST-ACT-DD",       143,   2,  ALPHA),
        new FieldSpec("FM1A5-ONL-TIME-LAST-ACT-HH",     145,   2,  ALPHA),
        new FieldSpec("FM1A5-ONL-TIME-LAST-ACT-MM",     147,   2,  ALPHA),
        new FieldSpec("FM1A5-ONL-TIME-LAST-ACT-SS",     149,   2,  ALPHA),
        new FieldSpec("FM1A5-STAT-CD",                  151,   1,  ALPHA),
        new FieldSpec("FM1A5-CLERK-NUM",                152,   4,  ALPHA),
        new FieldSpec("FM1A5-ERR-CD-1",                 156,   5,  ALPHA),
        new FieldSpec("FM1A5-ERR-CD-2",                 161,   5,  ALPHA),
        new FieldSpec("FM1A5-ERR-CD-3",                 166,   5,  ALPHA),
        new FieldSpec("FM1A5-ERR-CD-4",                 171,   5,  ALPHA),
        new FieldSpec("FM1A5-ERR-CD-5",                 176,   5,  ALPHA),
        new FieldSpec("FM1A5-LINE-BUS",                 181,   1,  ALPHA),
        new FieldSpec("FM1A5-SYS-INP-SRC",              182,   2,  ALPHA),
        new FieldSpec("FM1A5-TRANS-IND",                184,   1,  ALPHA),
        new FieldSpec("FM1A5-PLAN-PROF-STND-IND",       185,   1,  ALPHA),
        new FieldSpec("FM1A5-TYPE-SUBM",                186,   1,  ALPHA),
        new FieldSpec("FM1A5-PLAN-PROF-ADJ-EDIT-IND",   187,   1,  ALPHA),
        new FieldSpec("FM1A5-NAT-OOA-CD",               188,   1,  ALPHA),
        new FieldSpec("FM1A5-INVEST-IND",               189,   1,  ALPHA),
        new FieldSpec("FM1A5-RMRK-CD",                  190,   3,  ALPHA),
        new FieldSpec("FM1A5-FMT-DB-POST-DT-CC",        193,   2,  ALPHA),
        new FieldSpec("FM1A5-FMT-DB-POST-DT-YY",        195,   2,  ALPHA),
        new FieldSpec("FM1A5-FMT-DB-POST-DT-MM",        197,   2,  ALPHA),
        new FieldSpec("FM1A5-FMT-DB-POST-DT-DD",        199,   2,  ALPHA),
        new FieldSpec("FM1A5-CFA-CD",                   201,   1,  ALPHA),
        new FieldSpec("FM1A5-CNTL-PLAN-CFA-ACCT-CD",    202,   2,  ALPHA),
        new FieldSpec("FM1A5-AEA-CD",                   204,   1,  ALPHA),
        new FieldSpec("FM1A5-ACCESS-FEE-CD",            205,   1,  ALPHA),
        new FieldSpec("FM1A5-RESUB-DF-IND",             206,   1,  ALPHA),
        new FieldSpec("FM1A5-ADJ-RCPT-DT-CC",           207,   2,  ALPHA),
        new FieldSpec("FM1A5-ADJ-RCPT-DT-YY",           209,   2,  ALPHA),
        new FieldSpec("FM1A5-ADJ-RCPT-DT-MM",           211,   2,  ALPHA),
        new FieldSpec("FM1A5-ADJ-RCPT-DT-DD",           213,   2,  ALPHA),
        new FieldSpec("FM1A5-BCP-PROD-TYPE",            215,   1,  ALPHA),
        new FieldSpec("FM1A5-PLAN-OWNER-IND",           216,   1,  ALPHA),
        new FieldSpec("FM1A5-RECYC-CTR",                217,   1,  NUMERIC_TEXT),
        new FieldSpec("FM1A5-EXCLUDE-PER-USER",         218,   1,  ALPHA),
        new FieldSpec("FM1A5-EXCLUDE-PER-BLUECD",       219,   1,  ALPHA),
        new FieldSpec("FM1A5-INTL-CD",                  220,   1,  ALPHA),
        new FieldSpec("FM1A5-ECR-IND",                  221,   1,  ALPHA),
        new FieldSpec("FM1A5-ADMIN-EXP-ALLW",           222,   5,  PACKED_DECIMAL, 2),
        new FieldSpec("FM1A5-DEL-MTD",                  227,   1,  ALPHA),
        new FieldSpec("FM1A5-UPF-PRC-EDIT-CD",          228,   1,  ALPHA),
        new FieldSpec("FM1A5-835-IND",                  229,   1,  ALPHA),
        new FieldSpec("FM1A5-ACCT-TYPE-CD",             230,   1,  ALPHA),
        new FieldSpec("FM1A5-EST-IND",                  231,   1,  ALPHA),
        new FieldSpec("FM1A5-BOID",                     232,   4,  ALPHA),
        new FieldSpec("FM1A5-INIT-TRANSM-MODE-CD",      236,   1,  ALPHA),
        new FieldSpec("FM1A5-SYS-CRT-CD",               237,   1,  ALPHA),
        new FieldSpec("FM1A5-SYS-UPDT-CD",              238,   1,  ALPHA),
        new FieldSpec("FM1A5-ICD-PROV-SUB-VER-IND",     239,   1,  ALPHA),
        new FieldSpec("FM1A5-FMT-CONV-IND",             240,   1,  ALPHA),
        new FieldSpec("FM1A5-PRFX-ACCT-ID-IND",         241,   1,  ALPHA),
        new FieldSpec("FM1A5-FILLER-1",                 242,  14,  ALPHA)
    );
    public static final List<FieldSpec> FM1B0 = List.of(
        new FieldSpec("FM1B0-SER-NUM-LOCAL-PLAN",        1,   3, ALPHA),
        new FieldSpec("FM1B0-SER-NUM-JULDT-CC",          4,   2, ALPHA),
        new FieldSpec("FM1B0-SER-NUM-JULDT-YY",          6,   2, ALPHA),
        new FieldSpec("FM1B0-SER-NUM-JULDT-DDD",         8,   3, ALPHA),
        new FieldSpec("FM1B0-SER-NUM-SEQUENCE",         11,   5, ALPHA),
        new FieldSpec("FM1B0-SER-NUM-SUFFIX",           16,   2, ALPHA),
        new FieldSpec("FM1B0-TRANS-ID",                 18,   2, ALPHA),
        new FieldSpec("FM1B0-TRANS-QUAL",               20,   2, ALPHA),
        new FieldSpec("FM1B0-REC-TYPE",                 22,   2, ALPHA),
        new FieldSpec("FM1B0-SEQ-NUM",                  24,   2, BINARY),
        new FieldSpec("FM1B0-TYPE-BILL",                26,   3, ALPHA),
        new FieldSpec("FM1B0-FED-TAX-ID-NUM",           29,   9, ALPHA),
        new FieldSpec("FM1B0-TYPE-FED-TAX-ID-NUM",      38,   1, ALPHA),
        new FieldSpec("FM1B0-BILL-PROV-LAST-NAME",      39,  20, ALPHA),
        new FieldSpec("FM1B0-BILL-PROV-FIRST-NAME",     59,  10, ALPHA),
        new FieldSpec("FM1B0-BILL-PROV-MID-INIT",       69,   1, ALPHA),
        new FieldSpec("FM1B0-CLM-SUB-ORG-NAME",         70,  31, ALPHA),
        new FieldSpec("FM1B0-BILL-PROV-ADDR-LN1",      101,  25, ALPHA),
        new FieldSpec("FM1B0-BILL-PROV-ADDR-LN2",      126,  25, ALPHA),
        new FieldSpec("FM1B0-BILL-PROV-CITY",          151,  15, ALPHA),
        new FieldSpec("FM1B0-BILL-PROV-ST",            166,   2, ALPHA),
        new FieldSpec("FM1B0-BILL-PROV-ZIP-CD5",       168,   5, ALPHA),
        new FieldSpec("FM1B0-BILL-PROV-ZIP-CD4",       173,   4, ALPHA),
        new FieldSpec("FM1B0-BCBS-PROV-NUM",           177,  13, ALPHA),
        new FieldSpec("FM1B0-BILL-NAME-IND",           190,   1, ALPHA),
        new FieldSpec("FM1B0-PROV-CNTRY-CD",           191,   4, ALPHA),
        new FieldSpec("FM1B0-PERF-PROV-TXNMY-CD-CLM",  195,  15, ALPHA),
        new FieldSpec("FM1B0-PROV-NPI",                210,  10, ALPHA),
        new FieldSpec("FM1B0-CUST-PRIMY-NTWK",         220,   4, ALPHA),
        new FieldSpec("FM1B0-CUST-SCNDY-NTWK",         224,   4, ALPHA),
        new FieldSpec("FM1B0-PERF-PROV-IHS-CLM-IND",   228,   1, ALPHA),
        new FieldSpec("FM1B0-MKT-ID-CLM",              229,   4, ALPHA),
        new FieldSpec("FM1B0-TIER-DESIG-IND-CLM",      233,   1, ALPHA),
        new FieldSpec("FM1B0-FILLER-1",                234,  22, ALPHA)
    );
    public static final List<FieldSpec> FM1B5 = List.of(
        new FieldSpec("FM1B5-SER-NUM-LOCAL-PLAN",        1,   3, ALPHA),
        new FieldSpec("FM1B5-SER-NUM-JULDT-CC",          4,   2, ALPHA),
        new FieldSpec("FM1B5-SER-NUM-JULDT-YY",          6,   2, ALPHA),
        new FieldSpec("FM1B5-SER-NUM-JULDT-DDD",         8,   3, ALPHA),
        new FieldSpec("FM1B5-SER-NUM-SEQUENCE",         11,   5, ALPHA),
        new FieldSpec("FM1B5-SER-NUM-SUFFIX",           16,   2, ALPHA),
        new FieldSpec("FM1B5-TRANS-ID",                 18,   2, ALPHA),
        new FieldSpec("FM1B5-TRANS-QUAL",               20,   2, ALPHA),
        new FieldSpec("FM1B5-REC-TYPE",                 22,   2, ALPHA),
        new FieldSpec("FM1B5-SEQ-NUM",                  24,   2, BINARY),
        new FieldSpec("FM1B5-PMT-RSTRCT-IND",           26,   1, ALPHA),
        new FieldSpec("FM1B5-AMB-PICK-UP-ADDR",         27,  25, ALPHA),
        new FieldSpec("FM1B5-AMB-PICK-UP-CITY",         52,  15, ALPHA),
        new FieldSpec("FM1B5-AMB-PICK-UP-ST",           67,   2, ALPHA),
        new FieldSpec("FM1B5-AMB-PICK-UP-ZIP",          69,   9, ALPHA),
        new FieldSpec("FM1B5-FILLER-1",                 78,  54, ALPHA),
        new FieldSpec("FM1B5-SERV-FAC-LOC-ST-CLM",     132,   2, ALPHA),
        new FieldSpec("FM1B5-SERV-FAC-LOC-ZIP5-CLM",   134,   5, ALPHA),
        new FieldSpec("FM1B5-SERV-FAC-LOC-ZIP4-CLM",   139,   4, ALPHA),
        new FieldSpec("FM1B5-SERV-FAC-LOC-NUM-CLM",    143,  13, ALPHA),
        new FieldSpec("FM1B5-SERV-LOC-NUM-QUAL-CLM",   156,   2, ALPHA),
        new FieldSpec("FM1B5-AMB-DROP-OFF-LOC-NAME",   158,  35, ALPHA),
        new FieldSpec("FM1B5-AMB-DROP-OFF-ADDR",       193,  25, ALPHA),
        new FieldSpec("FM1B5-AMB-DROP-OFF-CITY",       218,  15, ALPHA),
        new FieldSpec("FM1B5-AMB-DROP-OFF-ST",         233,   2, ALPHA),
        new FieldSpec("FM1B5-AMB-DROP-OFF-ZIP",        235,   9, ALPHA),
        new FieldSpec("FM1B5-FILLER-2",                244,  12, ALPHA)
    );
    public static final List<FieldSpec> FM1C0 = List.of(
        new FieldSpec("FM1C0-SER-NUM-LOCAL-PLAN",        1,   3, ALPHA),
        new FieldSpec("FM1C0-SER-NUM-JULDT-CC",          4,   2, ALPHA),
        new FieldSpec("FM1C0-SER-NUM-JULDT-YY",          6,   2, ALPHA),
        new FieldSpec("FM1C0-SER-NUM-JULDT-DDD",         8,   3, ALPHA),
        new FieldSpec("FM1C0-SER-NUM-SEQUENCE",         11,   5, ALPHA),
        new FieldSpec("FM1C0-SER-NUM-SUFFIX",           16,   2, ALPHA),
        new FieldSpec("FM1C0-TRANS-ID",                 18,   2, ALPHA),
        new FieldSpec("FM1C0-TRANS-QUAL",               20,   2, ALPHA),
        new FieldSpec("FM1C0-REC-TYPE",                 22,   2, ALPHA),
        new FieldSpec("FM1C0-SEQ-NUM",                  24,   2, BINARY),
        new FieldSpec("FM1C0-PAT-LAST-NAME",            26,  20, ALPHA),
        new FieldSpec("FM1C0-PAT-FIRST-NAME",           46,  10, ALPHA),
        new FieldSpec("FM1C0-PAT-MID-INIT",             56,   1, ALPHA),
        new FieldSpec("FM1C0-PAT-SEX",                  57,   1, ALPHA),
        new FieldSpec("FM1C0-PAT-BRT-DT-CC",            58,   2, ALPHA),
        new FieldSpec("FM1C0-PAT-BRT-DT-YY",            60,   2, ALPHA),
        new FieldSpec("FM1C0-PAT-BRT-DT-MM",            62,   2, ALPHA),
        new FieldSpec("FM1C0-PAT-BRT-DT-DD",            64,   2, ALPHA),
        new FieldSpec("FM1C0-PAT-MAR-STAT-CD",          66,   1, ALPHA),
        new FieldSpec("FM1C0-PAT-ADDR-LN-1",            67,  25, ALPHA),
        new FieldSpec("FM1C0-PAT-ADDR-LN-2",            92,  25, ALPHA),
        new FieldSpec("FM1C0-PAT-CITY",                117,  15, ALPHA),
        new FieldSpec("FM1C0-PAT-ST",                  132,   2, ALPHA),
        new FieldSpec("FM1C0-PAT-ZIP-CD5",             134,   5, ALPHA),
        new FieldSpec("FM1C0-PAT-ZIP-CD4",             139,   4, ALPHA),
        new FieldSpec("FM1C0-ADM-DT-CC",               143,   2, ALPHA),
        new FieldSpec("FM1C0-ADM-DT-YY",               145,   2, ALPHA),
        new FieldSpec("FM1C0-ADM-DT-MM",               147,   2, ALPHA),
        new FieldSpec("FM1C0-ADM-DT-DD",               149,   2, ALPHA),
        new FieldSpec("FM1C0-DISCHRG-DT-CC",           151,   2, ALPHA),
        new FieldSpec("FM1C0-DISCHRG-DT-YY",           153,   2, ALPHA),
        new FieldSpec("FM1C0-DISCHRG-DT-MM",           155,   2, ALPHA),
        new FieldSpec("FM1C0-DISCHRG-DT-DD",           157,   2, ALPHA),
        new FieldSpec("FM1C0-DT-ACC-ONSET-ILL-CC",     159,   2, ALPHA),
        new FieldSpec("FM1C0-DT-ACC-ONSET-ILL-YY",     161,   2, ALPHA),
        new FieldSpec("FM1C0-DT-ACC-ONSET-ILL-MM",     163,   2, ALPHA),
        new FieldSpec("FM1C0-DT-ACC-ONSET-ILL-DD",     165,   2, ALPHA),
        new FieldSpec("FM1C0-WORK-COMP-IND",           167,   1, ALPHA),
        new FieldSpec("FM1C0-AUTO-OTH-ACC-CD",         168,   1, ALPHA),
        new FieldSpec("FM1C0-EMER-CD",                 169,   1, ALPHA),
        new FieldSpec("FM1C0-OTH-CARR-IND",            170,   1, ALPHA),
        new FieldSpec("FM1C0-SERV-ELIG-CD-CLM-1",      171,   1, ALPHA),
        new FieldSpec("FM1C0-SERV-ELIG-CD-CLM-2",      172,   1, ALPHA),
        new FieldSpec("FM1C0-SERV-ELIG-CD-CLM-3",      173,   1, ALPHA),
        new FieldSpec("FM1C0-SERV-ELIG-CD-CLM-4",      174,   1, ALPHA),
        new FieldSpec("FM1C0-FILLER-1",                175,  81, ALPHA)
    );
    public static final List<FieldSpec> FM1D0 = List.of(
        new FieldSpec("FM1D0-SER-NUM-LOCAL-PLAN",        1,   3, ALPHA),
        new FieldSpec("FM1D0-SER-NUM-JULDT-CC",          4,   2, ALPHA),
        new FieldSpec("FM1D0-SER-NUM-JULDT-YY",          6,   2, ALPHA),
        new FieldSpec("FM1D0-SER-NUM-JULDT-DDD",         8,   3, ALPHA),
        new FieldSpec("FM1D0-SER-NUM-SEQUENCE",         11,   5, ALPHA),
        new FieldSpec("FM1D0-SER-NUM-SUFFIX",           16,   2, ALPHA),
        new FieldSpec("FM1D0-TRANS-ID",                 18,   2, ALPHA),
        new FieldSpec("FM1D0-TRANS-QUAL",               20,   2, ALPHA),
        new FieldSpec("FM1D0-REC-TYPE",                 22,   2, ALPHA),
        new FieldSpec("FM1D0-SEQ-NUM",                  24,   2, BINARY),
        new FieldSpec("FM1D0-PAT-REL-SUB",              26,   2, ALPHA),
        new FieldSpec("FM1D0-SUB-LAST-NAME",            28,  20, ALPHA),
        new FieldSpec("FM1D0-SUB-FIRST-NAME",           48,  10, ALPHA),
        new FieldSpec("FM1D0-SUB-MID-INIT",             58,   1, ALPHA),
        new FieldSpec("FM1D0-SUB-BRT-DT-CC",            59,   2, ALPHA),
        new FieldSpec("FM1D0-SUB-BRT-DT-YY",            61,   2, ALPHA),
        new FieldSpec("FM1D0-SUB-BRT-DT-MM",            63,   2, ALPHA),
        new FieldSpec("FM1D0-SUB-BRT-DT-DD",            65,   2, ALPHA),
        new FieldSpec("FM1D0-SUB-ID-PFX-1-3",           67,   3, ALPHA),
        new FieldSpec("FM1D0-SUB-ID-SUFX-4-17",         70,  14, ALPHA),
        new FieldSpec("FM1D0-SUB-ADDR-LN-1",            84,  25, ALPHA),
        new FieldSpec("FM1D0-SUB-ADDR-LN-2",           109,  25, ALPHA),
        new FieldSpec("FM1D0-SUB-CITY",                134,  15, ALPHA),
        new FieldSpec("FM1D0-SUB-ZIP-CD5",             149,   5, ALPHA),
        new FieldSpec("FM1D0-SUB-ZIP-CD4",             154,   4, ALPHA),
        new FieldSpec("FM1D0-SUB-GRP-NUM",             158,   9, ALPHA),
        new FieldSpec("FM1D0-SEC-PAYOR-PRC-QUAL",      167,   1, ALPHA),
        new FieldSpec("FM1D0-REL-INFO-CD",             168,   1, ALPHA),
        new FieldSpec("FM1D0-ASGNMT-BNFT-IND",         169,   1, ALPHA),
        new FieldSpec("FM1D0-MPPQ-CD-ASGN",            170,   1, ALPHA),
        new FieldSpec("FM1D0-MPPQ-CD-UNASGN",          171,   1, ALPHA),
        new FieldSpec("FM1D0-COND-CD-1",               172,   2, ALPHA),
        new FieldSpec("FM1D0-COND-CD-2",               174,   2, ALPHA),
        new FieldSpec("FM1D0-COND-CD-3",               176,   2, ALPHA),
        new FieldSpec("FM1D0-COND-CD-4",               178,   2, ALPHA),
        new FieldSpec("FM1D0-COND-CD-5",               180,   2, ALPHA),
        new FieldSpec("FM1D0-COND-CD-6",               182,   2, ALPHA),
        new FieldSpec("FM1D0-COND-CD-7",               184,   2, ALPHA),
        new FieldSpec("FM1D0-COND-CD-8",               186,   2, ALPHA),
        new FieldSpec("FM1D0-COND-CD-9",               188,   2, ALPHA),
        new FieldSpec("FM1D0-COND-CD-10",              190,   2, ALPHA),
        new FieldSpec("FM1D0-COND-CD-11",              192,   2, ALPHA),
        new FieldSpec("FM1D0-COND-CD-12",              194,   2, ALPHA),
        new FieldSpec("FM1D0-SF-INFO-ONLY-MSG-CD-1",   196,   4, ALPHA),
        new FieldSpec("FM1D0-SF-INFO-ONLY-MSG-CD-2",   200,   4, ALPHA),
        new FieldSpec("FM1D0-SF-INFO-ONLY-MSG-CD-3",   204,   4, ALPHA),
        new FieldSpec("FM1D0-SF-INFO-ONLY-MSG-CD-4",   208,   4, ALPHA),
        new FieldSpec("FM1D0-SF-INFO-ONLY-MSG-CD-5",   212,   4, ALPHA),
        new FieldSpec("FM1D0-MED-ASGNMT-IND",          216,   1, ALPHA),
        new FieldSpec("FM1D0-FILLER-1",                217,  39, ALPHA)
    );
    public static final List<FieldSpec> FM1D1 = List.of(
        new FieldSpec("FM1D1-SER-NUM-LOCAL-PLAN",        1,   3, ALPHA),
        new FieldSpec("FM1D1-SER-NUM-JULDT-CC",          4,   2, ALPHA),
        new FieldSpec("FM1D1-SER-NUM-JULDT-YY",          6,   2, ALPHA),
        new FieldSpec("FM1D1-SER-NUM-JULDT-DDD",         8,   3, ALPHA),
        new FieldSpec("FM1D1-SER-NUM-SEQUENCE",         11,   5, ALPHA),
        new FieldSpec("FM1D1-SER-NUM-SUFFIX",           16,   2, ALPHA),
        new FieldSpec("FM1D1-TRANS-ID",                 18,   2, ALPHA),
        new FieldSpec("FM1D1-TRANS-QUAL",               20,   2, ALPHA),
        new FieldSpec("FM1D1-REC-TYPE",                 22,   2, ALPHA),
        new FieldSpec("FM1D1-SEQ-NUM",                  24,   2, BINARY),
        new FieldSpec("FM1D1-PAT-REL-OTH-INS",          26,   2, ALPHA),
        new FieldSpec("FM1D1-OTH-INS-LAST-NAME",        28,  20, ALPHA),
        new FieldSpec("FM1D1-OTH-INS-ID-NUM",           48,  17, ALPHA),
        new FieldSpec("FM1D1-OTH-PAYER-NAME",           65,  16, ALPHA),
        new FieldSpec("FM1D1-CLM-OTH-CARR-FNCL-CD",     81,   1, ALPHA),
        new FieldSpec("FM1D1-SRC-PMT-CD",               82,   2, ALPHA),
        new FieldSpec("FM1D1-CNTL-PLAN-CD",             84,   3, ALPHA),
        new FieldSpec("FM1D1-MED-CLM-NUM",              87,  12, ALPHA),
        new FieldSpec("FM1D1-MED-CLM-REJ-CD-CLM",       99,   5, ALPHA),
        new FieldSpec("FM1D1-FILLER-1",                104, 152, ALPHA)
    );
    public static final List<FieldSpec> FM1D2 = List.of(
    	    new FieldSpec("FM1D2-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
    	    new FieldSpec("FM1D2-SER-NUM-JULDT-CC", 4, 2, ALPHA),
    	    new FieldSpec("FM1D2-SER-NUM-JULDT-YY", 6, 2, ALPHA),
    	    new FieldSpec("FM1D2-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
    	    new FieldSpec("FM1D2-SER-NUM-SEQUENCE", 11, 5, ALPHA),
    	    new FieldSpec("FM1D2-SER-NUM-SUFFIX", 16, 2, ALPHA),
    	    new FieldSpec("FM1D2-TRANS-ID", 18, 2, ALPHA),
    	    new FieldSpec("FM1D2-TRANS-QUAL", 20, 2, ALPHA),
    	    new FieldSpec("FM1D2-REC-TYPE", 22, 2, ALPHA),
    	    new FieldSpec("FM1D2-SEQ-NUM", 24, 2, BINARY),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-1", 26, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-2", 28, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-3", 30, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-4", 32, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-5", 34, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-6", 36, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-7", 38, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-8", 40, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-9", 42, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-10", 44, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-11", 46, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-12", 48, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-13", 50, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-14", 52, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-15", 54, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-CD-CLM-16", 56, 2, ALPHA),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-1", 58, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-2", 64, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-3", 70, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-4", 76, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-5", 82, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-6", 88, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-7", 94, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-8", 100, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-9", 106, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-10", 112, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-11", 118, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-12", 124, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-13", 130, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-14", 136, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-15", 142, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-OPL-VAL-AMT-CLM-16", 148, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1D2-FILLER-1", 154, 102, ALPHA)
    	);
    public static final List<FieldSpec> FM1D3 = List.of(
        new FieldSpec("FM1D3-SER-NUM-LOCAL-PLAN",        1,   3, ALPHA),
        new FieldSpec("FM1D3-SER-NUM-JULDT-CC",          4,   2, ALPHA),
        new FieldSpec("FM1D3-SER-NUM-JULDT-YY",          6,   2, ALPHA),
        new FieldSpec("FM1D3-SER-NUM-JULDT-DDD",         8,   3, ALPHA),
        new FieldSpec("FM1D3-SER-NUM-SEQUENCE",         11,   5, ALPHA),
        new FieldSpec("FM1D3-SER-NUM-SUFFIX",           16,   2, ALPHA),
        new FieldSpec("FM1D3-TRANS-ID",                 18,   2, ALPHA),
        new FieldSpec("FM1D3-TRANS-QUAL",               20,   2, ALPHA),
        new FieldSpec("FM1D3-REC-TYPE",                 22,   2, ALPHA),
        new FieldSpec("FM1D3-SEQ-NUM",                  24,   2, BINARY),
        new FieldSpec("FM1D3-CLM-ADJ-GP-CD-CLM-PAYA-1", 26,   2, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-RSN-CD-CLM-PAYA-1",28,   5, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-AMT-CLM-PAYA-1",   33,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1D3-CLM-ADJ-GP-CD-CLM-PAYA-2", 39,   2, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-RSN-CD-CLM-PAYA-2",41,   5, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-AMT-CLM-PAYA-2",   46,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1D3-CLM-ADJ-GP-CD-CLM-PAYA-3", 52,   2, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-RSN-CD-CLM-PAYA-3",54,   5, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-AMT-CLM-PAYA-3",   59,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1D3-CLM-ADJ-GP-CD-CLM-PAYA-4", 65,   2, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-RSN-CD-CLM-PAYA-4",67,   5, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-AMT-CLM-PAYA-4",   72,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1D3-CLM-ADJ-GP-CD-CLM-PAYA-5", 78,   2, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-RSN-CD-CLM-PAYA-5",80,   5, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-AMT-CLM-PAYA-5",   85,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1D3-CLM-ADJ-GP-CD-CLM-PAYA-6", 91,   2, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-RSN-CD-CLM-PAYA-6",93,   5, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-AMT-CLM-PAYA-6",   98,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1D3-FILLER-1",                 104, 26, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-GP-CD-CLM-PAYB-1", 130,  2, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-RSN-CD-CLM-PAYB-1",132,  5, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-AMT-CLM-PAYB-1",   137,  6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1D3-CLM-ADJ-GP-CD-CLM-PAYB-2", 143,  2, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-RSN-CD-CLM-PAYB-2",145,  5, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-AMT-CLM-PAYB-2",   150,  6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1D3-CLM-ADJ-GP-CD-CLM-PAYB-3", 156,  2, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-RSN-CD-CLM-PAYB-3",158,  5, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-AMT-CLM-PAYB-3",   163,  6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1D3-CLM-ADJ-GP-CD-CLM-PAYB-4", 169,  2, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-RSN-CD-CLM-PAYB-4",171,  5, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-AMT-CLM-PAYB-4",   176,  6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1D3-CLM-ADJ-GP-CD-CLM-PAYB-5", 182,  2, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-RSN-CD-CLM-PAYB-5",184,  5, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-AMT-CLM-PAYB-5",   189,  6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1D3-CLM-ADJ-GP-CD-CLM-PAYB-6", 195,  2, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-RSN-CD-CLM-PAYB-6",197,  5, ALPHA),
        new FieldSpec("FM1D3-CLM-ADJ-AMT-CLM-PAYB-6",   202,  6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1D3-FILLER-2",                 208, 48, ALPHA)
    );
    public static final List<FieldSpec> FM1E0 = List.of(
        new FieldSpec("FM1E0-SER-NUM-LOCAL-PLAN",        1,   3, ALPHA),
        new FieldSpec("FM1E0-SER-NUM-JULDT-CC",          4,   2, ALPHA),
        new FieldSpec("FM1E0-SER-NUM-JULDT-YY",          6,   2, ALPHA),
        new FieldSpec("FM1E0-SER-NUM-JULDT-DDD",         8,   3, ALPHA),
        new FieldSpec("FM1E0-SER-NUM-SEQUENCE",         11,   5, ALPHA),
        new FieldSpec("FM1E0-SER-NUM-SUFFIX",           16,   2, ALPHA),
        new FieldSpec("FM1E0-TRANS-ID",                 18,   2, ALPHA),
        new FieldSpec("FM1E0-TRANS-QUAL",               20,   2, ALPHA),
        new FieldSpec("FM1E0-REC-TYPE",                 22,   2, ALPHA),
        new FieldSpec("FM1E0-SEQ-NUM",                  24,   2, BINARY),
        new FieldSpec("FM1E0-PAT-CNTL-NUM",             26,  20, ALPHA),
        new FieldSpec("FM1E0-SERV-FACIL-NAME",          46,  31, ALPHA),
        new FieldSpec("FM1E0-SERV-FACIL-NUM",           77,  13, ALPHA),
        new FieldSpec("FM1E0-TOT-CHRG",                 90,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1E0-PAT-PAID-AMT",             96,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1E0-UNABLE-WORK-FROM-DT-CC",  102,   2, ALPHA),
        new FieldSpec("FM1E0-UNABLE-WORK-FROM-DT-YY",  104,   2, ALPHA),
        new FieldSpec("FM1E0-UNABLE-WORK-FROM-DT-MM",  106,   2, ALPHA),
        new FieldSpec("FM1E0-UNABLE-WORK-FROM-DT-DD",  108,   2, ALPHA),
        new FieldSpec("FM1E0-UNABLE-WORK-TO-DT-CC",    110,   2, ALPHA),
        new FieldSpec("FM1E0-UNABLE-WORK-TO-DT-YY",    112,   2, ALPHA),
        new FieldSpec("FM1E0-UNABLE-WORK-TO-DT-MM",    114,   2, ALPHA),
        new FieldSpec("FM1E0-UNABLE-WORK-TO-DT-DD",    116,   2, ALPHA),
        new FieldSpec("FM1E0-BNFT-MGT-TRTMT-AUTH-NUM", 118,  25, ALPHA),
        new FieldSpec("FM1E0-SIGN-FILE-IND",           143,   1, ALPHA),
        new FieldSpec("FM1E0-ACCESS-FEE-PCT",          144,   3, PACKED_DECIMAL, 2),
        new FieldSpec("FM1E0-POS-IND",                 147,   1, ALPHA),
        new FieldSpec("FM1E0-ATTACH-IND",              148,   1, ALPHA),
        new FieldSpec("FM1E0-SPEC-PGM-CD",             149,   2, ALPHA),
        new FieldSpec("FM1E0-PERF-PROV-NUM-CLM",       151,  13, ALPHA),
        new FieldSpec("FM1E0-PERF-PROV-NAME-CLM",      164,  31, ALPHA),
        new FieldSpec("FM1E0-PERF-PROV-OFC-ZIP-CD5",   195,   5, ALPHA),
        new FieldSpec("FM1E0-PERF-PROV-OFC-ZIP-CD4",   200,   4, ALPHA),
        new FieldSpec("FM1E0-PERF-PROV-SPEC-CLM",      204,   2, ALPHA),
        new FieldSpec("FM1E0-PERF-PROV-TYPE-CLM",      206,   2, ALPHA),
        new FieldSpec("FM1E0-CLASS-PROV-CLM",          208,   1, ALPHA),
        new FieldSpec("FM1E0-PERF-PROV-POS-IND-CLM",   209,   1, ALPHA),
        new FieldSpec("FM1E0-PPO-AVBL",                210,   1, ALPHA),
        new FieldSpec("FM1E0-INDV-CASE-MGMT-STAT",     211,   1, ALPHA),
        new FieldSpec("FM1E0-HOST-OPL-PROV-ARRNG-CD",  212,   1, ALPHA),
        new FieldSpec("FM1E0-TOOTH-NUM-CLM",           213,   2, ALPHA),
        new FieldSpec("FM1E0-TOOTH-STAT",              215,   2, ALPHA),
        new FieldSpec("FM1E0-PERF-PROV-NPI-CLM",       217,  10, ALPHA),
        new FieldSpec("FM1E0-FILLER-1",                227,  29, ALPHA)
    );
    public static final List<FieldSpec> FM1E1 = List.of(
        new FieldSpec("FM1E1-SER-NUM-LOCAL-PLAN",       1,   3, ALPHA),
        new FieldSpec("FM1E1-SER-NUM-JULDT-CC",         4,   2, ALPHA),
        new FieldSpec("FM1E1-SER-NUM-JULDT-YY",         6,   2, ALPHA),
        new FieldSpec("FM1E1-SER-NUM-JULDT-DDD",        8,   3, ALPHA),
        new FieldSpec("FM1E1-SER-NUM-SEQUENCE",        11,   5, ALPHA),
        new FieldSpec("FM1E1-SER-NUM-SUFFIX",          16,   2, ALPHA),
        new FieldSpec("FM1E1-TRANS-ID",                18,   2, ALPHA),
        new FieldSpec("FM1E1-TRANS-QUAL",              20,   2, ALPHA),
        new FieldSpec("FM1E1-REC-TYPE",                22,   2, ALPHA),
        new FieldSpec("FM1E1-SEQ-NUM",                 24,   2, BINARY),
        new FieldSpec("FM1E1-SF-MSG-CD-CLM-1",         26,   4, ALPHA),
        new FieldSpec("FM1E1-SF-MSG-CD-CLM-2",         30,   4, ALPHA),
        new FieldSpec("FM1E1-SF-MSG-CD-CLM-3",         34,   4, ALPHA),
        new FieldSpec("FM1E1-SF-MSG-CD-CLM-4",         38,   4, ALPHA),
        new FieldSpec("FM1E1-SF-MSG-CD-CLM-5",         42,   4, ALPHA),
        new FieldSpec("FM1E1-SPEC-PRC-COND-CD-CLM-1",   46,   3, ALPHA),
        new FieldSpec("FM1E1-SPEC-PRC-COND-CD-CLM-2",   49,   3, ALPHA),
        new FieldSpec("FM1E1-SPEC-PRC-COND-CD-CLM-3",   52,   3, ALPHA),
        new FieldSpec("FM1E1-SPEC-PRC-COND-CD-CLM-4",   55,   3, ALPHA),
        new FieldSpec("FM1E1-SPEC-PRC-COND-CD-CLM-5",   58,   3, ALPHA),
        new FieldSpec("FM1E1-SPEC-PRC-COND-AMT-CLM-1",  61,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1E1-SPEC-PRC-COND-AMT-CLM-2",  67,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1E1-SPEC-PRC-COND-AMT-CLM-3",  73,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1E1-SPEC-PRC-COND-AMT-CLM-4",  79,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1E1-SPEC-PRC-COND-AMT-CLM-5",  85,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1E1-SPEC-PRC-COND-PCT-CLM-1",  91,   5, PACKED_DECIMAL, 5),
        new FieldSpec("FM1E1-SPEC-PRC-COND-PCT-CLM-2",  96,   5, PACKED_DECIMAL, 5),
        new FieldSpec("FM1E1-SPEC-PRC-COND-PCT-CLM-3", 101,   5, PACKED_DECIMAL, 5),
        new FieldSpec("FM1E1-SPEC-PRC-COND-PCT-CLM-4", 106,   5, PACKED_DECIMAL, 5),
        new FieldSpec("FM1E1-SPEC-PRC-COND-PCT-CLM-5", 111,   5, PACKED_DECIMAL, 5),
        new FieldSpec("FM1E1-PREDETRMN-BNFT-ID-CLM",   116,  30, ALPHA),
        new FieldSpec("FM1E1-SPEC-PRC-COND-DAYS-1",    146,   3, NUMERIC_TEXT),
        new FieldSpec("FM1E1-SPEC-PRC-COND-DAYS-2",    149,   3, NUMERIC_TEXT),
        new FieldSpec("FM1E1-SPEC-PRC-COND-DAYS-3",    152,   3, NUMERIC_TEXT),
        new FieldSpec("FM1E1-SPEC-PRC-COND-DAYS-4",    155,   3, NUMERIC_TEXT),
        new FieldSpec("FM1E1-SPEC-PRC-COND-DAYS-5",    158,   3, NUMERIC_TEXT),
        new FieldSpec("FM1E1-FILLER-2",                161,  95, ALPHA)
    );
    public static final List<FieldSpec> FM1E2 = List.of(
        new FieldSpec("FM1E2-SER-NUM-LOCAL-PLAN",        1,   3, ALPHA),
        new FieldSpec("FM1E2-SER-NUM-JULDT-CC",          4,   2, ALPHA),
        new FieldSpec("FM1E2-SER-NUM-JULDT-YY",          6,   2, ALPHA),
        new FieldSpec("FM1E2-SER-NUM-JULDT-DDD",         8,   3, ALPHA),
        new FieldSpec("FM1E2-SER-NUM-SEQUENCE",         11,   5, ALPHA),
        new FieldSpec("FM1E2-SER-NUM-SUFFIX",           16,   2, ALPHA),
        new FieldSpec("FM1E2-TRANS-ID",                 18,   2, ALPHA),
        new FieldSpec("FM1E2-TRANS-QUAL",               20,   2, ALPHA),
        new FieldSpec("FM1E2-REC-TYPE",                 22,   2, ALPHA),
        new FieldSpec("FM1E2-SEQ-NUM",                  24,   2, BINARY),
        new FieldSpec("FM1E2-ICD-DIAG-CD-1",            26,   7, ALPHA),
        new FieldSpec("FM1E2-ICD-DIAG-CD-2",            33,   7, ALPHA),
        new FieldSpec("FM1E2-ICD-DIAG-CD-3",            40,   7, ALPHA),
        new FieldSpec("FM1E2-ICD-DIAG-CD-4",            47,   7, ALPHA),
        new FieldSpec("FM1E2-ICD-DIAG-CD-5",            54,   7, ALPHA),
        new FieldSpec("FM1E2-ICD-DIAG-CD-6",            61,   7, ALPHA),
        new FieldSpec("FM1E2-ICD-DIAG-CD-7",            68,   7, ALPHA),
        new FieldSpec("FM1E2-ICD-DIAG-CD-8",            75,   7, ALPHA),
        new FieldSpec("FM1E2-ICD-DIAG-CD-9",            82,   7, ALPHA),
        new FieldSpec("FM1E2-ICD-DIAG-CD-10",           89,   7, ALPHA),
        new FieldSpec("FM1E2-ICD-DIAG-CD-11",           96,   7, ALPHA),
        new FieldSpec("FM1E2-ICD-DIAG-CD-12",          103,   7, ALPHA),
        new FieldSpec("FM1E2-ANES-PROC-CD-1",          110,   5, ALPHA),
        new FieldSpec("FM1E2-ANES-PROC-CD-2",          115,   5, ALPHA),
        new FieldSpec("FM1E2-FILLER-1",                120, 136, ALPHA)
    );
    public static final List<FieldSpec> FM1E6 = List.of(
        new FieldSpec("FM1E6-SER-NUM-LOCAL-PLAN",        1,   3, ALPHA),
        new FieldSpec("FM1E6-SER-NUM-JULDT-CC",          4,   2, ALPHA),
        new FieldSpec("FM1E6-SER-NUM-JULDT-YY",          6,   2, ALPHA),
        new FieldSpec("FM1E6-SER-NUM-JULDT-DDD",         8,   3, ALPHA),
        new FieldSpec("FM1E6-SER-NUM-SEQUENCE",         11,   5, ALPHA),
        new FieldSpec("FM1E6-SER-NUM-SUFFIX",           16,   2, ALPHA),
        new FieldSpec("FM1E6-TRANS-ID",                 18,   2, ALPHA),
        new FieldSpec("FM1E6-TRANS-QUAL",               20,   2, ALPHA),
        new FieldSpec("FM1E6-REC-TYPE",                 22,   2, ALPHA),
        new FieldSpec("FM1E6-SEQ-NUM",                  24,   2, BINARY),
        new FieldSpec("FM1E6-SPEC-NOTE-TRNSM-IND",      26,   1, ALPHA),
        new FieldSpec("FM1E6-SPEC-NOTE-CD",             27,   5, ALPHA),
        new FieldSpec("FM1E6-SPEC-NOTE-DATA",           32, 215, ALPHA),
        new FieldSpec("FM1E6-FILLER-1",                247,   9, ALPHA)
    );
    public static final List<FieldSpec> FM1F0 = List.of(
        new FieldSpec("FM1F0-SER-NUM-LOCAL-PLAN",       1,   3, ALPHA),
        new FieldSpec("FM1F0-SER-NUM-JULDT-CC",         4,   2, ALPHA),
        new FieldSpec("FM1F0-SER-NUM-JULDT-YY",         6,   2, ALPHA),
        new FieldSpec("FM1F0-SER-NUM-JULDT-DDD",        8,   3, ALPHA),
        new FieldSpec("FM1F0-SER-NUM-SEQUENCE",        11,   5, ALPHA),
        new FieldSpec("FM1F0-SER-NUM-SUFFIX",          16,   2, ALPHA),
        new FieldSpec("FM1F0-TRANS-ID",                18,   2, ALPHA),
        new FieldSpec("FM1F0-TRANS-QUAL",              20,   2, ALPHA),
        new FieldSpec("FM1F0-REC-TYPE",                22,   2, ALPHA),
        new FieldSpec("FM1F0-SEQ-NUM",                 24,   2, BINARY),
        new FieldSpec("FM1F0-DT-SERV-START-CC",        26,   2, ALPHA),
        new FieldSpec("FM1F0-DT-SERV-START-YY",        28,   2, ALPHA),
        new FieldSpec("FM1F0-DT-SERV-START-MM",        30,   2, ALPHA),
        new FieldSpec("FM1F0-DT-SERV-START-DD",        32,   2, ALPHA),
        new FieldSpec("FM1F0-DT-SERV-END-CC",          34,   2, ALPHA),
        new FieldSpec("FM1F0-DT-SERV-END-YY",          36,   2, ALPHA),
        new FieldSpec("FM1F0-DT-SERV-END-MM",          38,   2, ALPHA),
        new FieldSpec("FM1F0-DT-SERV-END-DD",          40,   2, ALPHA),
        new FieldSpec("FM1F0-PLACE-SERV",              42,   2, ALPHA),
        new FieldSpec("FM1F0-TYPE-SERV",               44,   3, ALPHA),
        new FieldSpec("FM1F0-HCPCS-PROC-CD",           47,   5, ALPHA),
        new FieldSpec("FM1F0-HCPCS-PROC-CD-MOD-1",     52,   2, ALPHA),
        new FieldSpec("FM1F0-HCPCS-PROC-CD-MOD-2",     54,   2, ALPHA),
        new FieldSpec("FM1F0-ICD-DIAG-CD-IND-1",       56,   2, ALPHA),
        new FieldSpec("FM1F0-ICD-DIAG-CD-IND-2",       58,   2, ALPHA),
        new FieldSpec("FM1F0-ICD-DIAG-CD-IND-3",       60,   2, ALPHA),
        new FieldSpec("FM1F0-ICD-DIAG-CD-IND-4",       62,   2, ALPHA),
        new FieldSpec("FM1F0-NUM-SERV",                64,   4, NUMERIC_TEXT),
        new FieldSpec("FM1F0-SERV-HH",                 68,   2, NUMERIC_TEXT),
        new FieldSpec("FM1F0-SERV-MM",                 70,   2, NUMERIC_TEXT),
        new FieldSpec("FM1F0-SERV-CHRG",               72,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F0-PERF-PROV-NUM-LN",        78,  13, ALPHA),
        new FieldSpec("FM1F0-PERF-PROV-LAST-NAME",     91,  20, ALPHA),
        new FieldSpec("FM1F0-PERF-PROV-FIRST-NAME",   111,  10, ALPHA),
        new FieldSpec("FM1F0-PERF-PROV-MID-NAME",     121,   1, ALPHA),
        new FieldSpec("FM1F0-PERF-PROV-OFC-ZIP-CD5",  122,   5, ALPHA),
        new FieldSpec("FM1F0-PERF-PROV-OFC-ZIP-CD4",  127,   4, ALPHA),
        new FieldSpec("FM1F0-PERF-PROV-SPEC-LN",      131,   2, ALPHA),
        new FieldSpec("FM1F0-PERF-PROV-TYPE-LN",      133,   2, ALPHA),
        new FieldSpec("FM1F0-ADDL-ANES-OTH-COND-CD",  135,   1, ALPHA),
        new FieldSpec("FM1F0-TOOTH-CD-AREA-1",        136,   2, ALPHA),
        new FieldSpec("FM1F0-TOOTH-CD-AREA-2",        138,   2, ALPHA),
        new FieldSpec("FM1F0-TOOTH-CD-AREA-3",        140,   2, ALPHA),
        new FieldSpec("FM1F0-TOOTH-CD-AREA-4",        142,   2, ALPHA),
        new FieldSpec("FM1F0-PERF-PROV-POS-IND-LN",   144,   1, ALPHA),
        new FieldSpec("FM1F0-CLASS-PROV-LN",          145,   1, ALPHA),
        new FieldSpec("FM1F0-SERV-FAC-LOC-ZIP5-LN",   146,   5, ALPHA),
        new FieldSpec("FM1F0-SERV-FAC-LOC-ZIP4-LN",   151,   4, ALPHA),
        new FieldSpec("FM1F0-SERV-FAC-LOC-NUM-LN",    155,  13, ALPHA),
        new FieldSpec("FM1F0-SERV-LOC-NUM-QUAL-LN",   168,   2, ALPHA),
        new FieldSpec("FM1F0-PERF-PROV-TXNMY-CD-LN",  170,  15, ALPHA),
        new FieldSpec("FM1F0-SERV-FAC-LOC-ST-LN",     185,   2, ALPHA),
        new FieldSpec("FM1F0-PERF-PROV-NPI-LN",       187,  10, ALPHA),
        new FieldSpec("FM1F0-HCPCS-PROC-CD-MOD-3",    197,   2, ALPHA),
        new FieldSpec("FM1F0-HCPCS-PROC-CD-MOD-4",    199,   2, ALPHA),
        new FieldSpec("FM1F0-NDC-CD",                 201,  13, ALPHA),
        new FieldSpec("FM1F0-LN-ITEM-CNTL-NUM",       214,  30, ALPHA),
        new FieldSpec("FM1F0-SERV-ELIG-CD-LN-1",      244,   1, ALPHA),
        new FieldSpec("FM1F0-SERV-ELIG-CD-LN-2",      245,   1, ALPHA),
        new FieldSpec("FM1F0-SERV-ELIG-CD-LN-3",      246,   1, ALPHA),
        new FieldSpec("FM1F0-SERV-ELIG-CD-LN-4",      247,   1, ALPHA),
        new FieldSpec("FM1F0-PERF-PROV-IHS-LN-IND",   248,   1, ALPHA),
        new FieldSpec("FM1F0-FILLER-1",               249,   7, ALPHA)
    );
    public static final List<FieldSpec> FM1F1 = List.of(
        new FieldSpec("FM1F1-SER-NUM-LOCAL-PLAN",       1,   3, ALPHA),
        new FieldSpec("FM1F1-SER-NUM-JULDT-CC",         4,   2, ALPHA),
        new FieldSpec("FM1F1-SER-NUM-JULDT-YY",         6,   2, ALPHA),
        new FieldSpec("FM1F1-SER-NUM-JULDT-DDD",        8,   3, ALPHA),
        new FieldSpec("FM1F1-SER-NUM-SEQUENCE",        11,   5, ALPHA),
        new FieldSpec("FM1F1-SER-NUM-SUFFIX",          16,   2, ALPHA),
        new FieldSpec("FM1F1-TRANS-ID",                18,   2, ALPHA),
        new FieldSpec("FM1F1-TRANS-QUAL",              20,   2, ALPHA),
        new FieldSpec("FM1F1-REC-TYPE",                22,   2, ALPHA),
        new FieldSpec("FM1F1-SEQ-NUM",                 24,   2, BINARY),
        new FieldSpec("FM1F1-DT-SERV-START-CC",        26,   2, ALPHA),
        new FieldSpec("FM1F1-DT-SERV-START-YY",        28,   2, ALPHA),
        new FieldSpec("FM1F1-DT-SERV-START-MM",        30,   2, ALPHA),
        new FieldSpec("FM1F1-DT-SERV-START-DD",        32,   2, ALPHA),
        new FieldSpec("FM1F1-DT-SERV-END-CC",          34,   2, ALPHA),
        new FieldSpec("FM1F1-DT-SERV-END-YY",          36,   2, ALPHA),
        new FieldSpec("FM1F1-DT-SERV-END-MM",          38,   2, ALPHA),
        new FieldSpec("FM1F1-DT-SERV-END-DD",          40,   2, ALPHA),
        new FieldSpec("FM1F1-PLACE-SERV",              42,   2, ALPHA),
        new FieldSpec("FM1F1-TYPE-SERV",               44,   3, ALPHA),
        new FieldSpec("FM1F1-HCPCS-PROC-CD",           47,   5, ALPHA),
        new FieldSpec("FM1F1-HCPCS-PROC-CD-MOD-1",     52,   2, ALPHA),
        new FieldSpec("FM1F1-HCPCS-PROC-CD-MOD-2",     54,   2, ALPHA),
        new FieldSpec("FM1F1-HCPCS-PROC-CD-MOD-3",     56,   2, ALPHA),
        new FieldSpec("FM1F1-HCPCS-PROC-CD-MOD-4",     58,   2, ALPHA),
        new FieldSpec("FM1F1-ICD-DIAG-CD-IND-1",       60,   1, ALPHA),
        new FieldSpec("FM1F1-ICD-DIAG-CD-IND-2",       61,   1, ALPHA),
        new FieldSpec("FM1F1-ICD-DIAG-CD-IND-3",       62,   1, ALPHA),
        new FieldSpec("FM1F1-ICD-DIAG-CD-IND-4",       63,   1, ALPHA),
        new FieldSpec("FM1F1-NUM-SERV",                64,   4, NUMERIC_TEXT),
        new FieldSpec("FM1F1-SERV-HH",                 68,   2, NUMERIC_TEXT),
        new FieldSpec("FM1F1-SERV-MM",                 70,   2, NUMERIC_TEXT),
        new FieldSpec("FM1F1-SERV-CHRG",               72,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F1-PERF-PROV-NUM-LN",        78,  13, ALPHA),
        new FieldSpec("FM1F1-PERF-PROV-LAST-NAME",     91,  20, ALPHA),
        new FieldSpec("FM1F1-PERF-PROV-FIRST-NAME",   111,  10, ALPHA),
        new FieldSpec("FM1F1-PERF-PROV-MID-NAME",     121,   1, ALPHA),
        new FieldSpec("FM1F1-PERF-PROV-OFC-ZIP-CD5",  122,   5, ALPHA),
        new FieldSpec("FM1F1-PERF-PROV-OFC-ZIP-CD4",  127,   4, ALPHA),
        new FieldSpec("FM1F1-PERF-PROV-SPEC-LN",      131,   2, ALPHA),
        new FieldSpec("FM1F1-PERF-PROV-TYPE-LN",      133,   2, ALPHA),
        new FieldSpec("FM1F1-PERF-PROV-TXNMY-CD-LN",  135,  15, ALPHA),
        new FieldSpec("FM1F1-SERV-FAC-LOC-NUM-LN",    150,  13, ALPHA),
        new FieldSpec("FM1F1-SERV-LOC-NUM-QUAL-LN",   163,   2, ALPHA),
        new FieldSpec("FM1F1-CLASS-PROV-LN",          165,   1, ALPHA),
        new FieldSpec("FM1F1-NDC-CD",                 166,  13, ALPHA),
        new FieldSpec("FM1F1-TOOTH-NUM-LN",           179,   2, ALPHA),
        new FieldSpec("FM1F1-TOOTH-SURFACE-CD-1",     181,   2, ALPHA),
        new FieldSpec("FM1F1-TOOTH-SURFACE-CD-2",     183,   2, ALPHA),
        new FieldSpec("FM1F1-TOOTH-SURFACE-CD-3",     185,   2, ALPHA),
        new FieldSpec("FM1F1-TOOTH-SURFACE-CD-4",     187,   2, ALPHA),
        new FieldSpec("FM1F1-TOOTH-SURFACE-CD-5",     189,   2, ALPHA),
        new FieldSpec("FM1F1-ORAL-CAVITY-DES-1",      191,   3, ALPHA),
        new FieldSpec("FM1F1-ORAL-CAVITY-DES-2",      194,   3, ALPHA),
        new FieldSpec("FM1F1-ORAL-CAVITY-DES-3",      197,   3, ALPHA),
        new FieldSpec("FM1F1-ORAL-CAVITY-DES-4",      200,   3, ALPHA),
        new FieldSpec("FM1F1-ORAL-CAVITY-DES-5",      203,   3, ALPHA),
        new FieldSpec("FM1F1-PROSTHETIC-CROWN",       206,   1, ALPHA),
        new FieldSpec("FM1F1-PREDETRMN-BNFT-IND",     207,   1, ALPHA),
        new FieldSpec("FM1F1-PREDETRMN-BNFT-ID-LN",   208,  30, ALPHA),
        new FieldSpec("FM1F1-PERF-PROV-NPI-LN",       238,  10, ALPHA),
        new FieldSpec("FM1F1-SERV-FAC-LOC-ST-LN",     248,   2, ALPHA),
        new FieldSpec("FM1F1-FILLER-1",               250,   6, ALPHA)
    );
    public static final List<FieldSpec> FM1F5 = List.of(
        new FieldSpec("FM1F5-SER-NUM-LOCAL-PLAN",       1,   3, ALPHA),
        new FieldSpec("FM1F5-SER-NUM-JULDT-CC",         4,   2, ALPHA),
        new FieldSpec("FM1F5-SER-NUM-JULDT-YY",         6,   2, ALPHA),
        new FieldSpec("FM1F5-SER-NUM-JULDT-DDD",        8,   3, ALPHA),
        new FieldSpec("FM1F5-SER-NUM-SEQUENCE",        11,   5, ALPHA),
        new FieldSpec("FM1F5-SER-NUM-SUFFIX",          16,   2, ALPHA),
        new FieldSpec("FM1F5-TRANS-ID",                18,   2, ALPHA),
        new FieldSpec("FM1F5-TRANS-QUAL",              20,   2, ALPHA),
        new FieldSpec("FM1F5-REC-TYPE",                22,   2, ALPHA),
        new FieldSpec("FM1F5-SEQ-NUM",                 24,   2, BINARY),
        new FieldSpec("FM1F5-SERV-ALLW-AMT",           26,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-PCT-FCTR-LN",             32,   3, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-PRC-MTD-LN",              35,   2, ALPHA),
        new FieldSpec("FM1F5-RULE-NUM-LN-1-3",         37,   3, ALPHA),
        new FieldSpec("FM1F5-RULE-NUM-LN-4-6",         40,   3, ALPHA),
        new FieldSpec("FM1F5-CAP-IND",                 43,   1, ALPHA),
        new FieldSpec("FM1F5-LOC-PLAN-REF-NUM",        44,  25, ALPHA),
        new FieldSpec("FM1F5-NUM-APPV-SERV",           69,   3, NUMERIC_TEXT),
        new FieldSpec("FM1F5-POS-PRC-LEV-IND",         72,   1, ALPHA),
        new FieldSpec("FM1F5-PREATH-PRECRT-STAT-IND",  73,   1, ALPHA),
        new FieldSpec("FM1F5-REF-STAT-IND",            74,   1, ALPHA),
        new FieldSpec("FM1F5-PERF-PCP-IND",            75,   1, ALPHA),
        new FieldSpec("FM1F5-REF-PCP-IND",             76,   2, ALPHA),
        new FieldSpec("FM1F5-REVIEW-DETER-COND-CD",    78,   2, ALPHA),
        new FieldSpec("FM1F5-PROV-BASE-PEN-AMT-LN",    80,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-PROV-BASE-PEN-PCT-LN",    86,   3, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-PRV-BASE-PEN-APL-RLE-LN", 89,   4, ALPHA),
        new FieldSpec("FM1F5-SF-MSG-CD-LN-1",          93,   4, ALPHA),
        new FieldSpec("FM1F5-SF-MSG-CD-LN-2",          97,   4, ALPHA),
        new FieldSpec("FM1F5-SF-MSG-CD-LN-3",         101,   4, ALPHA),
        new FieldSpec("FM1F5-SF-MSG-CD-LN-4",         105,   4, ALPHA),
        new FieldSpec("FM1F5-SF-MSG-CD-LN-5",         109,   4, ALPHA),
        new FieldSpec("FM1F5-SPEC-PRC-COND-CD-LN-1",  113,   3, ALPHA),
        new FieldSpec("FM1F5-SPEC-PRC-COND-CD-LN-2",  116,   3, ALPHA),
        new FieldSpec("FM1F5-SPEC-PRC-COND-CD-LN-3",  119,   3, ALPHA),
        new FieldSpec("FM1F5-SPEC-PRC-COND-CD-LN-4",  122,   3, ALPHA),
        new FieldSpec("FM1F5-SPEC-PRC-COND-CD-LN-5",  125,   3, ALPHA),
        new FieldSpec("FM1F5-SPEC-PRC-COND-AMT-LN-1", 128,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-SPEC-PRC-COND-AMT-LN-2", 134,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-SPEC-PRC-COND-AMT-LN-3", 140,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-SPEC-PRC-COND-AMT-LN-4", 146,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-SPEC-PRC-COND-AMT-LN-5", 152,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-SPEC-PRC-COND-PCT-LN-1", 158,   5, PACKED_DECIMAL, 5),
        new FieldSpec("FM1F5-SPEC-PRC-COND-PCT-LN-2", 163,   5, PACKED_DECIMAL, 5),
        new FieldSpec("FM1F5-SPEC-PRC-COND-PCT-LN-3", 168,   5, PACKED_DECIMAL, 5),
        new FieldSpec("FM1F5-SPEC-PRC-COND-PCT-LN-4", 173,   5, PACKED_DECIMAL, 5),
        new FieldSpec("FM1F5-SPEC-PRC-COND-PCT-LN-5", 178,   5, PACKED_DECIMAL, 5),
        new FieldSpec("FM1F5-PPO-PRV-TYP-AVL-LN",     183,   1, ALPHA),
        new FieldSpec("FM1F5-CLM-ADJ-GP-CD-LN-PAYB-1",184,   2, ALPHA),
        new FieldSpec("FM1F5-CLM-ADJ-RSN-CD-LN-PAYB-1",186,   5, ALPHA),
        new FieldSpec("FM1F5-CLM-ADJ-AMT-LN-PAYB-1",  191,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-CLM-ADJ-GP-CD-LN-PAYB-2",197,   2, ALPHA),
        new FieldSpec("FM1F5-CLM-ADJ-RSN-CD-LN-PAYB-2",199,   5, ALPHA),
        new FieldSpec("FM1F5-CLM-ADJ-AMT-LN-PAYB-2",  204,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-CLM-ADJ-GP-CD-LN-PAYB-3",210,   2, ALPHA),
        new FieldSpec("FM1F5-CLM-ADJ-RSN-CD-LN-PAYB-3",212,   5, ALPHA),
        new FieldSpec("FM1F5-CLM-ADJ-AMT-LN-PAYB-3",  217,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-CLM-ADJ-GP-CD-LN-PAYB-4",223,   2, ALPHA),
        new FieldSpec("FM1F5-CLM-ADJ-RSN-CD-LN-PAYB-4",225,   5, ALPHA),
        new FieldSpec("FM1F5-CLM-ADJ-AMT-LN-PAYB-4",  230,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-CLM-ADJ-GP-CD-LN-PAYB-5",236,   2, ALPHA),
        new FieldSpec("FM1F5-CLM-ADJ-RSN-CD-LN-PAYB-5",238,   5, ALPHA),
        new FieldSpec("FM1F5-CLM-ADJ-AMT-LN-PAYB-5",  243,   6, PACKED_DECIMAL, 2),
        new FieldSpec("FM1F5-INCL-GROUPING-NBR",      249,   2, ALPHA),
        new FieldSpec("FM1F5-ACT-AMB-MILEAGE",        251,   3, PACKED_DECIMAL, 1),
        new FieldSpec("FM1F5-TIER-DESIG-IND-LN",      254,   1, ALPHA),
        new FieldSpec("FM1F5-FILLER-1",               255,   1, ALPHA)
    );
    public static final List<FieldSpec> FM1F6 = List.of(
    	    new FieldSpec("FM1F6-SER-NUM-LOCAL-PLAN", 1, 3, ALPHA),
    	    new FieldSpec("FM1F6-SER-NUM-JULDT-CC", 4, 2, ALPHA),
    	    new FieldSpec("FM1F6-SER-NUM-JULDT-YY", 6, 2, ALPHA),
    	    new FieldSpec("FM1F6-SER-NUM-JULDT-DDD", 8, 3, ALPHA),
    	    new FieldSpec("FM1F6-SER-NUM-SEQUENCE", 11, 5, ALPHA),
    	    new FieldSpec("FM1F6-SER-NUM-SUFFIX", 16, 2, ALPHA),
    	    new FieldSpec("FM1F6-TRANS-ID", 18, 2, ALPHA),
    	    new FieldSpec("FM1F6-TRANS-QUAL", 20, 2, ALPHA),
    	    new FieldSpec("FM1F6-REC-TYPE", 22, 2, ALPHA),
    	    new FieldSpec("FM1F6-SEQ-NUM", 24, 2, BINARY),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-1", 26, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-2", 28, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-3", 30, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-4", 32, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-5", 34, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-6", 36, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-7", 38, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-8", 40, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-9", 42, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-10", 44, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-11", 46, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-12", 48, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-13", 50, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-14", 52, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-15", 54, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-CD-LN-16", 56, 2, ALPHA),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-1", 58, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-2", 64, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-3", 70, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-4", 76, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-5", 82, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-6", 88, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-7", 94, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-8", 100, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-9", 106, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-10", 112, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-11", 118, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-12", 124, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-13", 130, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-14", 136, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-15", 142, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-OPL-VAL-AMT-LN-16", 148, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-CLM-ADJ-GP-CD-LN-PAYA-1", 154, 2, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-RSN-CD-LN-PAYA-1", 156, 5, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-AMT-LN-PAYA-1", 161, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-CLM-ADJ-GP-CD-LN-PAYA-2", 167, 2, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-RSN-CD-LN-PAYA-2", 169, 5, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-AMT-LN-PAYA-2", 174, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-CLM-ADJ-GP-CD-LN-PAYA-3", 180, 2, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-RSN-CD-LN-PAYA-3", 182, 5, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-AMT-LN-PAYA-3", 187, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-CLM-ADJ-GP-CD-LN-PAYA-4", 193, 2, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-RSN-CD-LN-PAYA-4", 195, 5, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-AMT-LN-PAYA-4", 200, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-CLM-ADJ-GP-CD-LN-PAYA-5", 206, 2, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-RSN-CD-LN-PAYA-5", 208, 5, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-AMT-LN-PAYA-5", 213, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-CLM-ADJ-GP-CD-LN-PAYA-6", 219, 2, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-RSN-CD-LN-PAYA-6", 221, 5, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-AMT-LN-PAYA-6", 226, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-CLM-ADJ-GP-CD-LN-PAYB", 232, 2, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-RSN-CD-LN-PAYB", 234, 5, ALPHA),
    	    new FieldSpec("FM1F6-CLM-ADJ-AMT-LN-PAYB", 239, 6, PACKED_DECIMAL, 2),
    	    new FieldSpec("FM1F6-BDC-MSG-CD-LN", 245, 4, ALPHA),
    	    new FieldSpec("FM1F6-FILLER-1", 249, 3, ALPHA),
    	    new FieldSpec("FM1F6-MKT-ID-LN", 252, 4, ALPHA)
    	);
    public static final List<FieldSpec> FM1G0 = List.of(
        new FieldSpec("FM1G0-SER-NUM-LOCAL-PLAN",       1,   3, ALPHA),
        new FieldSpec("FM1G0-SER-NUM-JULDT-CC",         4,   2, ALPHA),
        new FieldSpec("FM1G0-SER-NUM-JULDT-YY",         6,   2, ALPHA),
        new FieldSpec("FM1G0-SER-NUM-JULDT-DDD",        8,   3, ALPHA),
        new FieldSpec("FM1G0-SER-NUM-SEQUENCE",        11,   5, ALPHA),
        new FieldSpec("FM1G0-SER-NUM-SUFFIX",          16,   2, ALPHA),
        new FieldSpec("FM1G0-TRANS-ID",                18,   2, ALPHA),
        new FieldSpec("FM1G0-TRANS-QUAL",              20,   2, ALPHA),
        new FieldSpec("FM1G0-REC-TYPE",                22,   2, ALPHA),
        new FieldSpec("FM1G0-SEQ-NUM",                 24,   2, BINARY),
        new FieldSpec("FM1G0-REF-PROV-LAST-NAME",      26,  20, ALPHA),
        new FieldSpec("FM1G0-REF-PROV-FIRST-NAME",     46,  10, ALPHA),
        new FieldSpec("FM1G0-REF-PROV-MID-INIT",       56,   1, ALPHA),
        new FieldSpec("FM1G0-REF-PROV-NUM",            57,  14, ALPHA),
        new FieldSpec("FM1G0-OTH-PHY-LAST-NAME",       71,  20, ALPHA),
        new FieldSpec("FM1G0-OTH-PHY-FIRST-NAME",      91,  10, ALPHA),
        new FieldSpec("FM1G0-OTH-PHY-MID-INIT",       101,   1, ALPHA),
        new FieldSpec("FM1G0-OTH-PHY-NUM",            102,  14, ALPHA),
        new FieldSpec("FM1G0-REF-PROV-NUM-QUAL",      116,   2, ALPHA),
        new FieldSpec("FM1G0-FILLER-1",               118, 138, ALPHA)
    );
    public static final List<FieldSpec> FM1X0 = List.of(
        new FieldSpec("FM1X0-SER-NUM-LOCAL-PLAN",       1,   3, ALPHA),
        new FieldSpec("FM1X0-SER-NUM-JULDT-CC",         4,   2, ALPHA),
        new FieldSpec("FM1X0-SER-NUM-JULDT-YY",         6,   2, ALPHA),
        new FieldSpec("FM1X0-SER-NUM-JULDT-DDD",        8,   3, ALPHA),
        new FieldSpec("FM1X0-SER-NUM-SEQUENCE",        11,   5, ALPHA),
        new FieldSpec("FM1X0-SER-NUM-SUFFIX",          16,   2, ALPHA),
        new FieldSpec("FM1X0-TRANS-ID",                18,   2, ALPHA),
        new FieldSpec("FM1X0-TRANS-QUAL",              20,   2, ALPHA),
        new FieldSpec("FM1X0-REC-TYPE",                22,   2, ALPHA),
        new FieldSpec("FM1X0-SEQ-NUM",                 24,   2, BINARY),
        new FieldSpec("FM1X0-PHY-REC-CNT",             26,   4, NUMERIC_TEXT),
        new FieldSpec("FM1X0-REC-TYPE-BX-CNT",         30,   2, NUMERIC_TEXT),
        new FieldSpec("FM1X0-REC-TYPE-CX-CNT",         32,   2, NUMERIC_TEXT),
        new FieldSpec("FM1X0-REC-TYPE-DX-CNT",         34,   2, NUMERIC_TEXT),
        new FieldSpec("FM1X0-REC-TYPE-EX-CNT",         36,   4, NUMERIC_TEXT),
        new FieldSpec("FM1X0-REC-TYPE-FX-CNT",         40,   4, NUMERIC_TEXT),
        new FieldSpec("FM1X0-REC-TYPE-GX-CNT",         44,   2, NUMERIC_TEXT),
        new FieldSpec("FM1X0-BLUE2-USER-ID",           46,  40, ALPHA),
        new FieldSpec("FM1X0-FILLER-1",                86, 170, ALPHA)
    );

}
